/**
 * fhir/account — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface AccountAkunPasienAsuransiDenganReferenceKeCoverageBody {
  resourceType?: string;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  name?: string;
  subject?: Array<Record<string, unknown>>;
  servicePeriod: {
    start?: string;
    end?: string;
  };
  owner: {
    reference?: string;
  };
  guarantor?: Array<Record<string, unknown>>;
  description?: string;
  coverage?: Array<Record<string, unknown>>;
}

/** Account - Akun Pasien - Asuransi, dengan reference ke Coverage — POST /Account */
export async function accountAkunPasienAsuransiDenganReferenceKeCoverage(
  client: SatuSehatClient, body: AccountAkunPasienAsuransiDenganReferenceKeCoverageBody
): Promise<FhirResource<"Account">> {
  return client.request("POST", "/Account", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Account">>;
}

/** Account - Menambahkan Secondary Coverage — PATCH /Account/:id */
export async function accountMenambahkanSecondaryCoverage(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Account/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
