/**
 * fhir/allergyintolerance — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface AllergyintoleranceCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
  };
}

/** AllergyIntolerance - Create — POST /AllergyIntolerance */
export async function allergyintoleranceCreate(
  client: SatuSehatClient, body: AllergyintoleranceCreateBody
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("POST", "/AllergyIntolerance", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface AllergyintoleranceSearchBySubjectWithWithoutAllergyCodeParams {
    patient?: string | number;
    code?: string | number;
}

/** AllergyIntolerance - Search by Subject with/without Allergy Code — GET /AllergyIntolerance */
export async function allergyintoleranceSearchBySubjectWithWithoutAllergyCode(
  client: SatuSehatClient, params: AllergyintoleranceSearchBySubjectWithWithoutAllergyCodeParams = {}
): Promise<FhirBundle<"AllergyIntolerance">> {
  return client.request("GET", "/AllergyIntolerance", {
    query: { patient: params.patient, code: params.code },
  }) as Promise<FhirBundle<"AllergyIntolerance">>;
}

/** AllergyIntolerance - Search by ID — GET /AllergyIntolerance/:id */
export async function allergyintoleranceSearchById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("GET", `/AllergyIntolerance/${id}`) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface AllergyintoleranceUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
  };
}

/** AllergyIntolerance - Update — PUT /AllergyIntolerance/:id */
export async function allergyintoleranceUpdate(
  client: SatuSehatClient, id: string, body: AllergyintoleranceUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/AllergyIntolerance/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** AllergyIntolerance - PATCH — PATCH /AllergyIntolerance/:id */
export async function allergyintolerancePatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/AllergyIntolerance/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
