/**
 * fhir/careplan — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CareplanPostBody {
  resourceType?: string;
  status?: string;
  intent?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  created?: string;
  author: {
    reference?: string;
  };
}

/** CarePlan - Post — POST /CarePlan */
export async function careplanPost(
  client: SatuSehatClient, body: CareplanPostBody
): Promise<FhirResource<"CarePlan">> {
  return client.request("POST", "/CarePlan", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CarePlan">>;
}

/** CarePlan - Search by ID Copy — GET /CarePlan/:id */
export async function careplanSearchByIdCopy(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"CarePlan">> {
  return client.request("GET", `/CarePlan/${id}`) as Promise<FhirResource<"CarePlan">>;
}

export interface CareplanSearchByPatientWithWithoutEncounterParams {
    subject?: string | number;
    encounter?: string | number;
}

/** CarePlan - Search by Patient with/without Encounter — GET /CarePlan */
export async function careplanSearchByPatientWithWithoutEncounter(
  client: SatuSehatClient, params: CareplanSearchByPatientWithWithoutEncounterParams = {}
): Promise<FhirBundle<"CarePlan">> {
  return client.request("GET", "/CarePlan", {
    query: { subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"CarePlan">>;
}

export interface CareplanUpdateBody {
  resourceType?: string;
  id?: string;
  status?: string;
  intent?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  created?: string;
  author: {
    reference?: string;
  };
}

/** CarePlan - UPDATE — PUT /CarePlan/:id */
export async function careplanUpdate(
  client: SatuSehatClient, id: string, body: CareplanUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/CarePlan/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** CarePlan - PATCH — PATCH /CarePlan/:id */
export async function careplanPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/CarePlan/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
