/**
 * fhir/chargeitem — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ChargeitemParatiroidektomiParsialBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  occurrencePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  quantity: {
    value?: number;
  };
  account?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** ChargeItem - Paratiroidektomi Parsial — POST /ChargeItem */
export async function chargeitemParatiroidektomiParsial(
  client: SatuSehatClient, body: ChargeitemParatiroidektomiParsialBody
): Promise<FhirResource<"ChargeItem">> {
  return client.request("POST", "/ChargeItem", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ChargeItem">>;
}

export interface ChargeitemGetByAccountAndPatientIdParams {
    account?: string | number;
    subject?: string | number;
}

/** ChargeItem - GET by Account and Patient_id — GET /ChargeItem */
export async function chargeitemGetByAccountAndPatientId(
  client: SatuSehatClient, params: ChargeitemGetByAccountAndPatientIdParams = {}
): Promise<FhirBundle<"ChargeItem">> {
  return client.request("GET", "/ChargeItem", {
    query: { account: params.account, subject: params.subject },
  }) as Promise<FhirBundle<"ChargeItem">>;
}

/** ChargeItem - GET By ID — GET /ChargeItem/:id */
export async function chargeitemGetById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"ChargeItem">> {
  return client.request("GET", `/ChargeItem/${id}`) as Promise<FhirResource<"ChargeItem">>;
}
