/**
 * fhir/claim — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ClaimDataKlaimAsuransiSwastaBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  use?: string;
  patient: {
    reference?: string;
  };
  billablePeriod: {
    start?: string;
    end?: string;
  };
  created?: string;
  enterer: {
    reference?: string;
  };
  insurer: {
    reference?: string;
  };
  provider: {
    reference?: string;
  };
  priority: {
    coding?: Array<Record<string, unknown>>;
  };
  payee: {
    type: {
      coding?: Array<Record<string, unknown>>;
    };
    party: {
      reference?: string;
    };
  };
  facility: {
    reference?: string;
  };
  supportingInfo?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  procedure?: Array<Record<string, unknown>>;
  insurance?: Array<Record<string, unknown>>;
  total: {
    value?: number;
    currency?: string;
  };
  extension?: Array<Record<string, unknown>>;
}

/** Claim - Data Klaim - Asuransi Swasta — POST /Claim */
export async function claimDataKlaimAsuransiSwasta(
  client: SatuSehatClient, body: ClaimDataKlaimAsuransiSwastaBody
): Promise<FhirResource<"Claim">> {
  return client.request("POST", "/Claim", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Claim">>;
}

export interface ClaimGetClaimByNoSepParams {
    identifier?: string | number;
}

/** Claim - GET Claim by No SEP — GET /Claim/ */
export async function claimGetClaimByNoSep(
  client: SatuSehatClient, params: ClaimGetClaimByNoSepParams = {}
): Promise<FhirBundle<"Claim">> {
  return client.request("GET", "/Claim/", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"Claim">>;
}
