/**
 * fhir/claimresponse — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ClaimresponseResponKlaimAsuransiSwastaBody {
  resourceType?: string;
  status?: string;
  identifier?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  subType: {
    coding?: Array<Record<string, unknown>>;
  };
  use?: string;
  patient: {
    reference?: string;
  };
  created?: string;
  insurer: {
    reference?: string;
  };
  requestor: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  payeeType: {
    coding?: Array<Record<string, unknown>>;
  };
  adjudication?: Array<Record<string, unknown>>;
  item?: Array<Record<string, unknown>>;
  total?: Array<Record<string, unknown>>;
  payment: {
    type: {
      coding?: Array<Record<string, unknown>>;
    };
    date?: string;
    amount: {
      value?: number;
      currency?: string;
    };
  };
}

/** ClaimResponse - Respon Klaim - Asuransi Swasta — POST /ClaimResponse */
export async function claimresponseResponKlaimAsuransiSwasta(
  client: SatuSehatClient, body: ClaimresponseResponKlaimAsuransiSwastaBody
): Promise<FhirResource<"ClaimResponse">> {
  return client.request("POST", "/ClaimResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClaimResponse">>;
}
