/**
 * fhir/clinicalimpression — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ClinicalimpressionCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  effectiveDateTime?: string;
  date?: string;
  assessor: {
    reference?: string;
  };
  problem?: Array<Record<string, unknown>>;
  investigation?: Array<Record<string, unknown>>;
  summary?: string;
  finding?: Array<Record<string, unknown>>;
  prognosisCodeableConcept?: Array<Record<string, unknown>>;
}

/** ClinicalImpression - Create — POST /ClinicalImpression */
export async function clinicalimpressionCreate(
  client: SatuSehatClient, body: ClinicalimpressionCreateBody
): Promise<FhirResource<"ClinicalImpression">> {
  return client.request("POST", "/ClinicalImpression", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClinicalImpression">>;
}

export interface ClinicalimpressionSearchBySubjectWithWithoutEncounterParams {
    subject?: string | number;
    encounter?: string | number;
}

/** ClinicalImpression- Search by Subject with/without Encounter — GET /ClinicalImpression */
export async function clinicalimpressionSearchBySubjectWithWithoutEncounter(
  client: SatuSehatClient, params: ClinicalimpressionSearchBySubjectWithWithoutEncounterParams = {}
): Promise<FhirBundle<"ClinicalImpression">> {
  return client.request("GET", "/ClinicalImpression", {
    query: { subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"ClinicalImpression">>;
}

/** ClinicalImpression - Search by ID — GET /ClinicalImpression/:id */
export async function clinicalimpressionSearchById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"ClinicalImpression">> {
  return client.request("GET", `/ClinicalImpression/${id}`) as Promise<FhirResource<"ClinicalImpression">>;
}

export interface ClinicalimpressionUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  effectiveDateTime?: string;
  date?: string;
  assessor: {
    reference?: string;
  };
  problem?: Array<Record<string, unknown>>;
  investigation?: Array<Record<string, unknown>>;
  summary?: string;
  finding?: Array<Record<string, unknown>>;
  prognosisCodeableConcept?: Array<Record<string, unknown>>;
}

/** ClinicalImpression - Update — PUT /ClinicalImpression/:id */
export async function clinicalimpressionUpdate(
  client: SatuSehatClient, id: string, body: ClinicalimpressionUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/ClinicalImpression/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** ClinicalImpression - PATCH — PATCH /ClinicalImpression/:id */
export async function clinicalimpressionPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/ClinicalImpression/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
