/**
 * fhir/composition — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CompositionEdukasiDietBody {
  resourceType?: string;
  identifier: {
    system?: string;
    value?: string;
  };
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  date?: string;
  author?: Array<Record<string, unknown>>;
  title?: string;
  custodian: {
    reference?: string;
  };
  section?: Array<Record<string, unknown>>;
}

/** Composition - Edukasi Diet — POST /Composition */
export async function compositionEdukasiDiet(
  client: SatuSehatClient, body: CompositionEdukasiDietBody
): Promise<FhirResource<"Composition">> {
  return client.request("POST", "/Composition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Composition">>;
}

export interface CompositionSearchBySubjectParams {
    subject?: string | number;
    encounter?: string | number;
}

/** Composition - Search by Subject — GET /Composition */
export async function compositionSearchBySubject(
  client: SatuSehatClient, params: CompositionSearchBySubjectParams = {}
): Promise<FhirBundle<"Composition">> {
  return client.request("GET", "/Composition", {
    query: { subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"Composition">>;
}

/** Composition - By ID — GET /Composition/:id */
export async function compositionById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Composition">> {
  return client.request("GET", `/Composition/${id}`) as Promise<FhirResource<"Composition">>;
}

export interface CompositionUpdateBody {
  resourceType?: string;
  id?: string;
  identifier: {
    system?: string;
    value?: string;
  };
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  date?: string;
  author?: Array<Record<string, unknown>>;
  title?: string;
  custodian: {
    reference?: string;
  };
  section?: Array<Record<string, unknown>>;
}

/** Composition - Update — PUT /Composition/:id */
export async function compositionUpdate(
  client: SatuSehatClient, id: string, body: CompositionUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Composition/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Composition - PATCH — PATCH /Composition/:id */
export async function compositionPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Composition/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
