/**
 * fhir/condition — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ConditionDiagnosisBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
}

/** Condition - Diagnosis — POST /Condition */
export async function conditionDiagnosis(
  client: SatuSehatClient, body: ConditionDiagnosisBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

export interface ConditionSearchBySubjectParams {
    subject?: string | number;
    encounter?: string | number;
}

/** Condition - Search by Subject — GET /Condition */
export async function conditionSearchBySubject(
  client: SatuSehatClient, params: ConditionSearchBySubjectParams = {}
): Promise<FhirBundle<"Condition">> {
  return client.request("GET", "/Condition", {
    query: { subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"Condition">>;
}

/** Condition - By ID — GET /Condition/:id */
export async function conditionById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Condition">> {
  return client.request("GET", `/Condition/${id}`) as Promise<FhirResource<"Condition">>;
}

export interface ConditionUpdateBody {
  resourceType?: string;
  id?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
}

/** Condition - Update — PUT /Condition/:id */
export async function conditionUpdate(
  client: SatuSehatClient, id: string, body: ConditionUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Condition/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Condition - Patch — PATCH /Condition/:id */
export async function conditionPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Condition/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
