/**
 * fhir/coverageeligibilityrequest — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CoverageeligibilityrequestGetByIdentifierParams {
    identifier?: string | number;
    patient?: string | number;
}

/** CoverageEligibilityRequest - GET By Identifier — GET /CoverageEligibilityRequest */
export async function coverageeligibilityrequestGetByIdentifier(
  client: SatuSehatClient, params: CoverageeligibilityrequestGetByIdentifierParams = {}
): Promise<FhirBundle<"CoverageEligibilityRequest">> {
  return client.request("GET", "/CoverageEligibilityRequest", {
    query: { identifier: params.identifier, patient: params.patient },
  }) as Promise<FhirBundle<"CoverageEligibilityRequest">>;
}

/** CoverageEligibilityRequest - GET Everything — GET /CoverageEligibilityRequest/{{CoverageEligibilityRequest_id}}/$everything */
export async function coverageeligibilityrequestGetEverything(
  client: SatuSehatClient, coverageeligibilityrequestId: string
): Promise<FhirBundle<"CoverageEligibilityRequest">> {
  return client.request("GET", `/CoverageEligibilityRequest/${coverageeligibilityrequestId}/$everything`) as Promise<FhirBundle<"CoverageEligibilityRequest">>;
}

export interface CoverageeligibilityrequestRequestSepKeAsuransiSwastaBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  priority: {
    coding?: Array<Record<string, unknown>>;
  };
  purpose?: Array<string>;
  patient: {
    reference?: string;
  };
  servicedDate?: string;
  created?: string;
  enterer: {
    reference?: string;
  };
  provider: {
    reference?: string;
  };
  insurer: {
    reference?: string;
  };
  facility: {
    reference?: string;
  };
  insurance?: Array<Record<string, unknown>>;
  supportingInfo?: Array<Record<string, unknown>>;
  contained?: Array<Record<string, unknown>>;
}

/** CoverageEligibilityRequest - Request SEP ke Asuransi Swasta — POST /CoverageEligibilityRequest */
export async function coverageeligibilityrequestRequestSepKeAsuransiSwasta(
  client: SatuSehatClient, body: CoverageeligibilityrequestRequestSepKeAsuransiSwastaBody
): Promise<FhirResource<"CoverageEligibilityRequest">> {
  return client.request("POST", "/CoverageEligibilityRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CoverageEligibilityRequest">>;
}
