/**
 * fhir/coverageeligibilityresponse — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CoverageeligibilityresponseResponseSepAsuransiPrimerBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  purpose?: Array<string>;
  patient: {
    reference?: string;
  };
  created?: string;
  requestor: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  insurer: {
    reference?: string;
  };
  insurance?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** CoverageEligibilityResponse - Response SEP - Asuransi Primer — POST /CoverageEligibilityResponse */
export async function coverageeligibilityresponseResponseSepAsuransiPrimer(
  client: SatuSehatClient, body: CoverageeligibilityresponseResponseSepAsuransiPrimerBody
): Promise<FhirResource<"CoverageEligibilityResponse">> {
  return client.request("POST", "/CoverageEligibilityResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CoverageEligibilityResponse">>;
}

export interface CoverageeligibilityresponseGetByIdRequestParams {
    request?: string | number;
}

/** CoverageEligibilityResponse - GET by ID Request — GET /CoverageEligibilityResponse/ */
export async function coverageeligibilityresponseGetByIdRequest(
  client: SatuSehatClient, params: CoverageeligibilityresponseGetByIdRequestParams = {}
): Promise<FhirBundle<"CoverageEligibilityResponse">> {
  return client.request("GET", "/CoverageEligibilityResponse/", {
    query: { request: params.request },
  }) as Promise<FhirBundle<"CoverageEligibilityResponse">>;
}
