/**
 * fhir/coverage — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CoverageMendapatkanDataKepesertaanParams {
    patient?: string | number;
    identifier?: string | number;
}

/** Coverage - Mendapatkan Data Kepesertaan — GET /Coverage */
export async function coverageMendapatkanDataKepesertaan(
  client: SatuSehatClient, params: CoverageMendapatkanDataKepesertaanParams = {}
): Promise<FhirBundle<"Coverage">> {
  return client.request("GET", "/Coverage", {
    query: { patient: params.patient, identifier: params.identifier },
  }) as Promise<FhirBundle<"Coverage">>;
}

export interface CoverageKepesertaanBpjsKBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  policyHolder: {
    reference?: string;
  };
  subscriber: {
    reference?: string;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - BPJS-K — POST /Coverage */
export async function coverageKepesertaanBpjsK(
  client: SatuSehatClient, body: CoverageKepesertaanBpjsKBody
): Promise<FhirResource<"Coverage">> {
  return client.request("POST", "/Coverage", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Coverage">>;
}
