/**
 * fhir/diagnosticreport — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface DiagnosticreportCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  result?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  specimen?: Array<Record<string, unknown>>;
  conclusionCode?: Array<Record<string, unknown>>;
}

/** DiagnosticReport - Create — POST /DiagnosticReport */
export async function diagnosticreportCreate(
  client: SatuSehatClient, body: DiagnosticreportCreateBody
): Promise<FhirResource<"DiagnosticReport">> {
  return client.request("POST", "/DiagnosticReport", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"DiagnosticReport">>;
}

export interface DiagnosticreportSearchBySubjectParams {
    subject?: string | number;
    encounter?: string | number;
    specimen?: string | number;
}

/** DiagnosticReport - Search by Subject — GET /DiagnosticReport */
export async function diagnosticreportSearchBySubject(
  client: SatuSehatClient, params: DiagnosticreportSearchBySubjectParams = {}
): Promise<FhirBundle<"DiagnosticReport">> {
  return client.request("GET", "/DiagnosticReport", {
    query: { subject: params.subject, encounter: params.encounter, specimen: params.specimen },
  }) as Promise<FhirBundle<"DiagnosticReport">>;
}

/** DiagnosticReport - By ID — GET /DiagnosticReport/:id */
export async function diagnosticreportById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"DiagnosticReport">> {
  return client.request("GET", `/DiagnosticReport/${id}`) as Promise<FhirResource<"DiagnosticReport">>;
}

export interface DiagnosticreportUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  result?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  specimen?: Array<Record<string, unknown>>;
  conclusionCode?: Array<Record<string, unknown>>;
}

/** DiagnosticReport - Update — PUT /DiagnosticReport/:id */
export async function diagnosticreportUpdate(
  client: SatuSehatClient, id: string, body: DiagnosticreportUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/DiagnosticReport/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** DiagnosticReport - PATCH — PATCH /DiagnosticReport/:id */
export async function diagnosticreportPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/DiagnosticReport/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
