/**
 * fhir/encounter — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface EncounterCreateBody {
  resourceType?: string;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  location?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  serviceProvider: {
    reference?: string;
  };
  identifier?: Array<Record<string, unknown>>;
}

/** Encounter - Create — POST /Encounter */
export async function encounterCreate(
  client: SatuSehatClient, body: EncounterCreateBody
): Promise<FhirResource<"Encounter">> {
  return client.request("POST", "/Encounter", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Encounter">>;
}

/** Encounter - By ID — GET /Encounter/:id */
export async function encounterById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Encounter">> {
  return client.request("GET", `/Encounter/${id}`) as Promise<FhirResource<"Encounter">>;
}

export interface EncounterBySubjectParams {
    subject?: string | number;
}

/** Encounter - by Subject — GET /Encounter */
export async function encounterBySubject(
  client: SatuSehatClient, params: EncounterBySubjectParams = {}
): Promise<FhirBundle<"Encounter">> {
  return client.request("GET", "/Encounter", {
    query: { subject: params.subject },
  }) as Promise<FhirBundle<"Encounter">>;
}

export interface EncounterUpdateInprogressBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
    end?: string;
  };
  location?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  serviceProvider: {
    reference?: string;
  };
  hospitalization: {
    dischargeDisposition: {
      coding?: Array<Record<string, unknown>>;
      text?: string;
    };
  };
}

/** Encounter - Update Inprogress — PUT /Encounter/:id */
export async function encounterUpdateInprogress(
  client: SatuSehatClient, id: string, body: EncounterUpdateInprogressBody
): Promise<FhirResource> {
  return client.request("PUT", `/Encounter/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Encounter - PATCH Array — PATCH /Encounter/:id */
export async function encounterPatchArray(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Encounter/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
