/**
 * fhir/episodeofcare — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface EpisodeofcareCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  statusHistory?: Array<Record<string, unknown>>;
  type?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  patient: {
    reference?: string;
    display?: string;
  };
  managingOrganization: {
    reference?: string;
  };
  period: {
    start?: string;
    end?: string;
  };
  careManager: {
    reference?: string;
    display?: string;
  };
}

/** EpisodeOfCare - Create — POST /EpisodeOfCare */
export async function episodeofcareCreate(
  client: SatuSehatClient, body: EpisodeofcareCreateBody
): Promise<FhirResource<"EpisodeOfCare">> {
  return client.request("POST", "/EpisodeOfCare", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"EpisodeOfCare">>;
}

export interface EpisodeofcareSearchBySubjectParams {
    subject?: string | number;
    organization?: string | number;
    careManager?: string | number;
}

/** EpisodeOfCare - Search by Subject — GET /EpisodeOfCare */
export async function episodeofcareSearchBySubject(
  client: SatuSehatClient, params: EpisodeofcareSearchBySubjectParams = {}
): Promise<FhirBundle<"EpisodeOfCare">> {
  return client.request("GET", "/EpisodeOfCare", {
    query: { subject: params.subject, organization: params.organization, "care-manager": params.careManager },
  }) as Promise<FhirBundle<"EpisodeOfCare">>;
}

/** EpisodeOfCare - Search by ID — GET /EpisodeOfCare/:id */
export async function episodeofcareSearchById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"EpisodeOfCare">> {
  return client.request("GET", `/EpisodeOfCare/${id}`) as Promise<FhirResource<"EpisodeOfCare">>;
}

export interface EpisodeofcareUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  statusHistory?: Array<Record<string, unknown>>;
  type?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  patient: {
    reference?: string;
    display?: string;
  };
  managingOrganization: {
    reference?: string;
  };
  period: {
    start?: string;
    end?: string;
  };
  careManager: {
    reference?: string;
    display?: string;
  };
}

/** EpisodeOfCare - Update — PUT /EpisodeOfCare/:id */
export async function episodeofcareUpdate(
  client: SatuSehatClient, id: string, body: EpisodeofcareUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/EpisodeOfCare/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** EpisodeOfCare - PATCH — PATCH /EpisodeOfCare/:id */
export async function episodeofcarePatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/EpisodeOfCare/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
