/**
 * fhir/imagingstudy — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ImagingstudyPostSingleImageBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  modality?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
  };
  started?: string;
  basedOn?: Array<Record<string, unknown>>;
  numberOfSeries?: number;
  numberOfInstances?: number;
  series?: Array<Record<string, unknown>>;
}

/** ImagingStudy - POST (Single Image) — POST /ImagingStudy */
export async function imagingstudyPostSingleImage(
  client: SatuSehatClient, body: ImagingstudyPostSingleImageBody
): Promise<FhirResource<"ImagingStudy">> {
  return client.request("POST", "/ImagingStudy", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ImagingStudy">>;
}

export interface ImagingstudyGetIdBasedOnAccessionNumberParams {
    identifier?: string | number;
}

/** ImagingStudy - Get ID based on Accession Number — GET /ImagingStudy */
export async function imagingstudyGetIdBasedOnAccessionNumber(
  client: SatuSehatClient, params: ImagingstudyGetIdBasedOnAccessionNumberParams = {}
): Promise<FhirBundle<"ImagingStudy">> {
  return client.request("GET", "/ImagingStudy", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"ImagingStudy">>;
}

export interface ImagingstudyPutMultipleImageBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  modality?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
  };
  started?: string;
  basedOn?: Array<Record<string, unknown>>;
  numberOfSeries?: number;
  numberOfInstances?: number;
  description?: string;
  series?: Array<Record<string, unknown>>;
}

/** ImagingStudy - PUT (Multiple Image) — PUT /ImagingStudy/:id */
export async function imagingstudyPutMultipleImage(
  client: SatuSehatClient, id: string, body: ImagingstudyPutMultipleImageBody
): Promise<FhirResource> {
  return client.request("PUT", `/ImagingStudy/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}
