/**
 * fhir/immunization — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ImmunizationImunisasiDilakukanOlehNakesBody {
  resourceType?: string;
  status?: string;
  vaccineCode: {
    coding?: Array<Record<string, unknown>>;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  occurrenceDateTime?: string;
  recorded?: string;
  primarySource?: boolean;
  reportOrigin: {
    coding?: Array<Record<string, unknown>>;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  protocolApplied?: Array<Record<string, unknown>>;
  encounter: {
    reference?: string;
  };
  reaction?: Array<Record<string, unknown>>;
  lotNumber?: string;
  route: {
    coding?: Array<Record<string, unknown>>;
  };
  doseQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  statusReason: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
}

/** Immunization : Imunisasi dilakukan oleh Nakes — POST /Immunization */
export async function immunizationImunisasiDilakukanOlehNakes(
  client: SatuSehatClient, body: ImmunizationImunisasiDilakukanOlehNakesBody
): Promise<FhirResource<"Immunization">> {
  return client.request("POST", "/Immunization", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Immunization">>;
}

export interface Observation02aKipiTerpantauNakesBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  valueCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** Observation #02a : KIPI terpantau Nakes — POST /Observation */
export async function observation02aKipiTerpantauNakes(
  client: SatuSehatClient, body: Observation02aKipiTerpantauNakesBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}

export interface ImmunizationSearchByPatientWithWithoutDateAdministeredParams {
    date?: string | number;
    patient?: string | number;
}

/** Immunization - Search by Patient with/without date administered — GET /Immunization */
export async function immunizationSearchByPatientWithWithoutDateAdministered(
  client: SatuSehatClient, params: ImmunizationSearchByPatientWithWithoutDateAdministeredParams = {}
): Promise<FhirBundle<"Immunization">> {
  return client.request("GET", "/Immunization", {
    query: { date: params.date, patient: params.patient },
  }) as Promise<FhirBundle<"Immunization">>;
}

/** Immunization - Search by ID — GET /Immunization/:id */
export async function immunizationSearchById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Immunization">> {
  return client.request("GET", `/Immunization/${id}`) as Promise<FhirResource<"Immunization">>;
}

export interface ImmunizationUpdateBody {
  resourceType?: string;
  id?: string;
  status?: string;
  vaccineCode: {
    coding?: Array<Record<string, unknown>>;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  occurrenceDateTime?: string;
  recorded?: string;
  primarySource?: boolean;
  location: {
    reference?: string;
    display?: string;
  };
  lotNumber?: string;
  route: {
    coding?: Array<Record<string, unknown>>;
  };
  doseQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  protocolApplied?: Array<Record<string, unknown>>;
}

/** Immunization - UPDATE — PUT /Immunization/:id */
export async function immunizationUpdate(
  client: SatuSehatClient, id: string, body: ImmunizationUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Immunization/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Immunization - PATCH — PATCH /Immunization/:id */
export async function immunizationPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Immunization/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
