/**
 * fhir/invoice — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface InvoiceInvoiceBody {
  resourceType?: string;
  status?: string;
  subject: {
    reference?: string;
  };
  date?: string;
  issuer: {
    reference?: string;
  };
  account: {
    reference?: string;
  };
  lineItem?: Array<Record<string, unknown>>;
  totalNet: {
    value?: number;
    currency?: string;
  };
}

/** Invoice - Invoice — POST /Invoice */
export async function invoiceInvoice(
  client: SatuSehatClient, body: InvoiceInvoiceBody
): Promise<FhirResource<"Invoice">> {
  return client.request("POST", "/Invoice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Invoice">>;
}
