/**
 * fhir/location — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

// Search/create/lookup already implemented once in src/common/*.ts.
export { createLocation, getLocation } from "../common/organization.js";

export interface LocationSearchByIdentifierParams {
    identifier?: string | number;
    name?: string | number;
    organization?: string | number;
}

/** Location - Search by Identifier — GET /Location */
export async function locationSearchByIdentifier(
  client: SatuSehatClient, params: LocationSearchByIdentifierParams = {}
): Promise<FhirBundle<"Location">> {
  return client.request("GET", "/Location", {
    query: { identifier: params.identifier, name: params.name, organization: params.organization },
  }) as Promise<FhirBundle<"Location">>;
}

export interface LocationUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  name?: string;
  description?: string;
  mode?: string;
  telecom?: Array<Record<string, unknown>>;
  address: {
    use?: string;
    line?: Array<string>;
    city?: string;
    postalCode?: string;
    country?: string;
    extension?: Array<Record<string, unknown>>;
  };
  physicalType: {
    coding?: Array<Record<string, unknown>>;
  };
  position: {
    longitude?: number;
    latitude?: number;
    altitude?: number;
  };
  managingOrganization: {
    reference?: string;
  };
}

/** Location - Update — PUT /Location/:id */
export async function locationUpdate(
  client: SatuSehatClient, id: string, body: LocationUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Location/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Location - Patch — PATCH /Location/:id */
export async function locationPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Location/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
