/**
 * fhir/medicationdispense — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface MedicationdispenseCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  authorizingPrescription?: Array<Record<string, unknown>>;
  quantity: {
    system?: string;
    code?: string;
    value?: number;
  };
  daysSupply: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  whenPrepared?: string;
  whenHandedOver?: string;
  dosageInstruction?: Array<Record<string, unknown>>;
}

/** MedicationDispense - Create — POST /MedicationDispense */
export async function medicationdispenseCreate(
  client: SatuSehatClient, body: MedicationdispenseCreateBody
): Promise<FhirResource<"MedicationDispense">> {
  return client.request("POST", "/MedicationDispense", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationDispense">>;
}

export interface MedicationdispenseSearchBySubjectParams {
    subject?: string | number;
    prescription?: string | number;
    context?: string | number;
}

/** MedicationDispense - Search by Subject — GET /MedicationDispense */
export async function medicationdispenseSearchBySubject(
  client: SatuSehatClient, params: MedicationdispenseSearchBySubjectParams = {}
): Promise<FhirBundle<"MedicationDispense">> {
  return client.request("GET", "/MedicationDispense", {
    query: { subject: params.subject, prescription: params.prescription, context: params.context },
  }) as Promise<FhirBundle<"MedicationDispense">>;
}

/** MedicationDispense - By ID — GET /MedicationDispense/:id */
export async function medicationdispenseById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"MedicationDispense">> {
  return client.request("GET", `/MedicationDispense/${id}`) as Promise<FhirResource<"MedicationDispense">>;
}

export interface MedicationdispenseUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  authorizingPrescription?: Array<Record<string, unknown>>;
  quantity: {
    system?: string;
    code?: string;
    value?: number;
  };
  daysSupply: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  whenPrepared?: string;
  whenHandedOver?: string;
  dosageInstruction?: Array<Record<string, unknown>>;
}

/** MedicationDispense - UPDATE — PUT /MedicationDispense/:id */
export async function medicationdispenseUpdate(
  client: SatuSehatClient, id: string, body: MedicationdispenseUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/MedicationDispense/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** MedicationDispense - PATCH — PATCH /MedicationDispense/:id */
export async function medicationdispensePatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/MedicationDispense/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
