/**
 * fhir/medication — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface MedicationCreateBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  status?: string;
  manufacturer: {
    reference?: string;
  };
  form: {
    coding?: Array<Record<string, unknown>>;
  };
  ingredient?: Array<Record<string, unknown>>;
  extension: Array<Record<string, unknown>>; /* required: see coding/medication.js medicationTypeExtension() */
}

/** Medication - Create — POST /Medication */
export async function medicationCreate(
  client: SatuSehatClient, body: MedicationCreateBody
): Promise<FhirResource<"Medication">> {
  return client.request("POST", "/Medication", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Medication">>;
}

/** Medication - By ID — GET /Medication/:id */
export async function medicationById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Medication">> {
  return client.request("GET", `/Medication/${id}`) as Promise<FhirResource<"Medication">>;
}

export interface MedicationUpdateBody {
  resourceType?: string;
  id?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  status?: string;
  manufacturer: {
    reference?: string;
  };
  form: {
    coding?: Array<Record<string, unknown>>;
  };
  ingredient?: Array<Record<string, unknown>>;
  extension: Array<Record<string, unknown>>; /* required: see coding/medication.js medicationTypeExtension() */
}

/** Medication - UPDATE — PUT /Medication/:id */
export async function medicationUpdate(
  client: SatuSehatClient, id: string, body: MedicationUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Medication/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Medication - PATCH — PATCH /Medication/:id */
export async function medicationPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Medication/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
