/**
 * fhir/medicationrequest — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface MedicationrequestCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  priority?: string;
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  reasonCode?: Array<Record<string, unknown>>;
  courseOfTherapyType: {
    coding?: Array<Record<string, unknown>>;
  };
  dosageInstruction?: Array<Record<string, unknown>>;
  dispenseRequest: {
    dispenseInterval: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    validityPeriod: {
      start?: string;
      end?: string;
    };
    numberOfRepeatsAllowed?: number;
    quantity: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    expectedSupplyDuration: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    performer: {
      reference?: string;
    };
  };
}

/** MedicationRequest - Create — POST /MedicationRequest */
export async function medicationrequestCreate(
  client: SatuSehatClient, body: MedicationrequestCreateBody
): Promise<FhirResource<"MedicationRequest">> {
  return client.request("POST", "/MedicationRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationRequest">>;
}

export interface MedicationrequestSearchBySubjectParams {
    subject?: string | number;
    encounter?: string | number;
}

/** MedicationRequest - Search by Subject — GET /MedicationRequest */
export async function medicationrequestSearchBySubject(
  client: SatuSehatClient, params: MedicationrequestSearchBySubjectParams = {}
): Promise<FhirBundle<"MedicationRequest">> {
  return client.request("GET", "/MedicationRequest", {
    query: { subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"MedicationRequest">>;
}

/** MedicationRequest - By ID — GET /MedicationRequest/:id */
export async function medicationrequestById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"MedicationRequest">> {
  return client.request("GET", `/MedicationRequest/${id}`) as Promise<FhirResource<"MedicationRequest">>;
}

export interface MedicationrequestPutBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  priority?: string;
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  reasonCode?: Array<Record<string, unknown>>;
  courseOfTherapyType: {
    coding?: Array<Record<string, unknown>>;
  };
  dosageInstruction?: Array<Record<string, unknown>>;
  dispenseRequest: {
    dispenseInterval: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    validityPeriod: {
      start?: string;
      end?: string;
    };
    numberOfRepeatsAllowed?: number;
    quantity: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    expectedSupplyDuration: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    performer: {
      reference?: string;
    };
  };
}

/** MedicationRequest - PUT — PUT /MedicationRequest/:id */
export async function medicationrequestPut(
  client: SatuSehatClient, id: string, body: MedicationrequestPutBody
): Promise<FhirResource> {
  return client.request("PUT", `/MedicationRequest/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** MedicationRequest - PATCH — PATCH /MedicationRequest/:id */
export async function medicationrequestPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/MedicationRequest/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
