/**
 * fhir/observation-ttv — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ObservationCreateBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  encounter: {
    reference?: string;
    display?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  valueQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
}

/** Observation - Create — POST /Observation */
export async function observationCreate(
  client: SatuSehatClient, body: ObservationCreateBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}

export interface ObservationSearchBySubjectParams {
    subject?: string | number;
    encounter?: string | number;
    basedOn?: string | number;
}

/** Observation - Search by Subject — GET /Observation */
export async function observationSearchBySubject(
  client: SatuSehatClient, params: ObservationSearchBySubjectParams = {}
): Promise<FhirBundle<"Observation">> {
  return client.request("GET", "/Observation", {
    query: { subject: params.subject, encounter: params.encounter, "based-on": params.basedOn },
  }) as Promise<FhirBundle<"Observation">>;
}

/** Observation - By ID — GET /Observation/:id */
export async function observationById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Observation">> {
  return client.request("GET", `/Observation/${id}`) as Promise<FhirResource<"Observation">>;
}

export interface ObservationUpdateBody {
  resourceType?: string;
  status?: string;
  id?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  valueQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
}

/** Observation - Update — PUT /Observation/:id */
export async function observationUpdate(
  client: SatuSehatClient, id: string, body: ObservationUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Observation/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Observation - PATCH — PATCH /Observation/:id */
export async function observationPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Observation/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
