/**
 * fhir/organization — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

// Search/create/lookup already implemented once in src/common/*.ts.
export { createOrganization, getOrganization } from "../common/organization.js";

export interface OrganizationSearchByNameParams {
    name?: string | number;
    partof?: string | number;
}

/** Organization - Search by Name — GET /Organization */
export async function organizationSearchByName(
  client: SatuSehatClient, params: OrganizationSearchByNameParams = {}
): Promise<FhirBundle<"Organization">> {
  return client.request("GET", "/Organization", {
    query: { name: params.name, partof: params.partof },
  }) as Promise<FhirBundle<"Organization">>;
}

export interface OrganizationUpdateBody {
  resourceType?: string;
  id?: string;
  active?: boolean;
  identifier?: Array<Record<string, unknown>>;
  type?: Array<Record<string, unknown>>;
  name?: string;
  telecom?: Array<Record<string, unknown>>;
  address?: Array<Record<string, unknown>>;
  partOf: {
    reference?: string;
  };
}

/** Organization - Update — PUT /Organization/:id */
export async function organizationUpdate(
  client: SatuSehatClient, id: string, body: OrganizationUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Organization/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Organization - Patch — PATCH /Organization/:id */
export async function organizationPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Organization/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
