/**
 * fhir/patient — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

// Search/create/lookup already implemented once in src/common/*.ts.
export { searchPatient } from "../common/search.js";

export interface PatientCreateByNikBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  active?: boolean;
  name?: Array<Record<string, unknown>>;
  telecom?: Array<Record<string, unknown>>;
  gender?: string;
  birthDate?: string;
  deceasedBoolean?: boolean;
  address?: Array<Record<string, unknown>>;
  maritalStatus: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  multipleBirthInteger?: number;
  contact?: Array<Record<string, unknown>>;
  communication?: Array<Record<string, unknown>>;
}

/** Patient - Create by NIK — POST /Patient */
export async function patientCreateByNik(
  client: SatuSehatClient, body: PatientCreateByNikBody
): Promise<FhirResource<"Patient">> {
  return client.request("POST", "/Patient", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Patient">>;
}

/** Patch Patient — PATCH /Patient/P20394850874 */
export async function patchPatient(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Patient/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
