/**
 * fhir/paymentnotice — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface PaymentnoticeNotifikasiPembayaranAsuransiBody {
  resourceType?: string;
  status?: string;
  request: {
    reference?: string;
  };
  created?: string;
  paymentDate?: string;
  provider: {
    reference?: string;
  };
  payee: {
    reference?: string;
  };
  recipient: {
    reference?: string;
  };
  amount: {
    value?: number;
    currency?: string;
  };
  payment: {
    reference?: string;
  };
  paymentStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  response: {
    reference?: string;
  };
}

/** PaymentNotice - Notifikasi Pembayaran - Asuransi — POST /PaymentNotice */
export async function paymentnoticeNotifikasiPembayaranAsuransi(
  client: SatuSehatClient, body: PaymentnoticeNotifikasiPembayaranAsuransiBody
): Promise<FhirResource<"PaymentNotice">> {
  return client.request("POST", "/PaymentNotice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentNotice">>;
}

export interface GetPaymentnoticeGetByIdClaimParams {
    request?: string | number;
}

/** GET PaymentNotice - GET By ID Claim — GET /PaymentNotice */
export async function getPaymentnoticeGetByIdClaim(
  client: SatuSehatClient, params: GetPaymentnoticeGetByIdClaimParams = {}
): Promise<FhirBundle<"PaymentNotice">> {
  return client.request("GET", "/PaymentNotice", {
    query: { request: params.request },
  }) as Promise<FhirBundle<"PaymentNotice">>;
}
