/**
 * fhir/paymentreconciliation — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface PaymentreconcilliationRekonsiliasiPembayaranAsuransiBody {
  resourceType?: string;
  status?: string;
  period: {
    start?: string;
    end?: string;
  };
  created?: string;
  paymentIssuer: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  paymentDate?: string;
  paymentAmount: {
    value?: number;
    currency?: string;
  };
  detail?: Array<Record<string, unknown>>;
  processNote?: Array<Record<string, unknown>>;
  requestor: {
    reference?: string;
  };
}

/** PaymentReconcilliation - Rekonsiliasi Pembayaran - Asuransi — POST /PaymentReconciliation */
export async function paymentreconcilliationRekonsiliasiPembayaranAsuransi(
  client: SatuSehatClient, body: PaymentreconcilliationRekonsiliasiPembayaranAsuransiBody
): Promise<FhirResource<"PaymentReconciliation">> {
  return client.request("POST", "/PaymentReconciliation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentReconciliation">>;
}

export interface GetPaymentreconciliationGetByIdClaimParams {
    detailRequest?: string | number;
}

/** GET PaymentReconciliation - GET By ID Claim — GET /PaymentReconciliation */
export async function getPaymentreconciliationGetByIdClaim(
  client: SatuSehatClient, params: GetPaymentreconciliationGetByIdClaimParams = {}
): Promise<FhirBundle<"PaymentReconciliation">> {
  return client.request("GET", "/PaymentReconciliation", {
    query: { "detail-request": params.detailRequest },
  }) as Promise<FhirBundle<"PaymentReconciliation">>;
}
