/**
 * fhir/procedure — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ProcedureCreateBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** Procedure - Create — POST /Procedure */
export async function procedureCreate(
  client: SatuSehatClient, body: ProcedureCreateBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}

export interface ProcedureSearchBySubjectParams {
    subject?: string | number;
    encounter?: string | number;
}

/** Procedure - Search by Subject — GET /Procedure */
export async function procedureSearchBySubject(
  client: SatuSehatClient, params: ProcedureSearchBySubjectParams = {}
): Promise<FhirBundle<"Procedure">> {
  return client.request("GET", "/Procedure", {
    query: { subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"Procedure">>;
}

/** Procedure - By ID — GET /Procedure/:id */
export async function procedureById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Procedure">> {
  return client.request("GET", `/Procedure/${id}`) as Promise<FhirResource<"Procedure">>;
}

export interface ProcedureUpdateBody {
  resourceType?: string;
  id?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** Procedure - Update — PUT /Procedure/:id */
export async function procedureUpdate(
  client: SatuSehatClient, id: string, body: ProcedureUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Procedure/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Procedure - PATCH — PATCH /Procedure/:id */
export async function procedurePatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Procedure/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
