/**
 * fhir/questionnaireresponse — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface QuestionnaireresponseCreateBody {
  resourceType?: string;
  questionnaire?: string;
  status?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authored?: string;
  author: {
    reference?: string;
  };
  source: {
    reference?: string;
  };
  item?: Array<Record<string, unknown>>;
}

/** QuestionnaireResponse - Create — POST /QuestionnaireResponse */
export async function questionnaireresponseCreate(
  client: SatuSehatClient, body: QuestionnaireresponseCreateBody
): Promise<FhirResource<"QuestionnaireResponse">> {
  return client.request("POST", "/QuestionnaireResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"QuestionnaireResponse">>;
}

export interface QuestionnaireresponseUpdateBody {
  resourceType?: string;
  id?: string;
  questionnaire?: string;
  status?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authored?: string;
  author: {
    reference?: string;
  };
  source: {
    reference?: string;
  };
  item?: Array<Record<string, unknown>>;
}

/** QuestionnaireResponse - Update — PUT /QuestionnaireResponse/:id */
export async function questionnaireresponseUpdate(
  client: SatuSehatClient, id: string, body: QuestionnaireresponseUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/QuestionnaireResponse/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

export interface QuestionnaireresponseSearchBySubjectEncounterParams {
    encounter?: string | number;
    patient?: string | number;
}

/** QuestionnaireResponse - Search by Subject & Encounter — GET /QuestionnaireResponse */
export async function questionnaireresponseSearchBySubjectEncounter(
  client: SatuSehatClient, params: QuestionnaireresponseSearchBySubjectEncounterParams = {}
): Promise<FhirBundle<"QuestionnaireResponse">> {
  return client.request("GET", "/QuestionnaireResponse", {
    query: { encounter: params.encounter, patient: params.patient },
  }) as Promise<FhirBundle<"QuestionnaireResponse">>;
}

/** QuestionnaireResponse - Search by Id — GET /QuestionnaireResponse/:id */
export async function questionnaireresponseSearchById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"QuestionnaireResponse">> {
  return client.request("GET", `/QuestionnaireResponse/${id}`) as Promise<FhirResource<"QuestionnaireResponse">>;
}
