/**
 * fhir/relatedperson — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface RelatedpersonPatientBayiDanNikIbuBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  active?: boolean;
  relationship?: Array<Record<string, unknown>>;
  patient: {
    reference?: string;
  };
  name?: Array<Record<string, unknown>>;
  telecom?: Array<Record<string, unknown>>;
  gender?: string;
  birthDate?: string;
  address?: Array<Record<string, unknown>>;
  communication?: Array<Record<string, unknown>>;
}

/** RelatedPerson - Patient Bayi dan NIK Ibu — POST /RelatedPerson */
export async function relatedpersonPatientBayiDanNikIbu(
  client: SatuSehatClient, body: RelatedpersonPatientBayiDanNikIbuBody
): Promise<FhirResource<"RelatedPerson">> {
  return client.request("POST", "/RelatedPerson", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"RelatedPerson">>;
}

export interface RelatedpersonUpdateBody {
  resourceType?: string;
  id?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  active?: boolean;
  relationship?: Array<Record<string, unknown>>;
  patient: {
    reference?: string;
  };
  name?: Array<Record<string, unknown>>;
  telecom?: Array<Record<string, unknown>>;
  gender?: string;
  birthDate?: string;
  address?: Array<Record<string, unknown>>;
  communication?: Array<Record<string, unknown>>;
}

/** RelatedPerson - Update — PUT /RelatedPerson/:id */
export async function relatedpersonUpdate(
  client: SatuSehatClient, id: string, body: RelatedpersonUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/RelatedPerson/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

export interface RelatedpersonGetByNikParams {
    identifier?: string | number;
}

/** RelatedPerson - Get by NIK — GET /RelatedPerson */
export async function relatedpersonGetByNik(
  client: SatuSehatClient, params: RelatedpersonGetByNikParams = {}
): Promise<FhirBundle<"RelatedPerson">> {
  return client.request("GET", "/RelatedPerson", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"RelatedPerson">>;
}

/** RelatedPerson - PATCH — PATCH /RelatedPerson/:id */
export async function relatedpersonPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/RelatedPerson/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
