/**
 * fhir/servicerequest — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ServicerequestLaboratoriumNonRujukanEksternalBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  occurrenceDateTime?: string;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  locationCode?: Array<Record<string, unknown>>;
  locationReference?: Array<Record<string, unknown>>;
  patientInstruction?: string;
}

/** ServiceRequest - Laboratorium Non Rujukan Eksternal — POST /ServiceRequest */
export async function servicerequestLaboratoriumNonRujukanEksternal(
  client: SatuSehatClient, body: ServicerequestLaboratoriumNonRujukanEksternalBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}

export interface ServicerequestSearchByIdentifierParams {
    identifier?: string | number;
    subject?: string | number;
    encounter?: string | number;
}

/** ServiceRequest - Search by Identifier — GET /ServiceRequest */
export async function servicerequestSearchByIdentifier(
  client: SatuSehatClient, params: ServicerequestSearchByIdentifierParams = {}
): Promise<FhirBundle<"ServiceRequest">> {
  return client.request("GET", "/ServiceRequest", {
    query: { identifier: params.identifier, subject: params.subject, encounter: params.encounter },
  }) as Promise<FhirBundle<"ServiceRequest">>;
}

/** ServiceRequest - By ID — GET /ServiceRequest/:id */
export async function servicerequestById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("GET", `/ServiceRequest/${id}`) as Promise<FhirResource<"ServiceRequest">>;
}

export interface ServicerequestUpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  occurrenceDateTime?: string;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
}

/** ServiceRequest - Update — PUT /ServiceRequest/:id */
export async function servicerequestUpdate(
  client: SatuSehatClient, id: string, body: ServicerequestUpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/ServiceRequest/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** ServiceRequest - PATCH — PATCH /ServiceRequest/:id */
export async function servicerequestPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/ServiceRequest/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
