/**
 * fhir/specimen — generated by scripts/generate-modules.mjs
 * from "00. FHIR Resource - Contoh Penggunaan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface SpecimenCreateNonRujukanBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  collection: {
    collectedDateTime?: string;
    extension?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  request?: Array<Record<string, unknown>>;
  receivedTime?: string;
  extension?: Array<Record<string, unknown>>;
}

/** Specimen - Create (Non Rujukan) — POST /Specimen */
export async function specimenCreateNonRujukan(
  client: SatuSehatClient, body: SpecimenCreateNonRujukanBody
): Promise<FhirResource<"Specimen">> {
  return client.request("POST", "/Specimen", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Specimen">>;
}

export interface SpecimenRujukanSampelWithReceivedtimeCollectororganizationBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  collection: {
    collectedDateTime?: string;
    extension?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  request?: Array<Record<string, unknown>>;
  receivedTime?: string;
  extension?: Array<Record<string, unknown>>;
}

/** Specimen - Rujukan Sampel (with ReceivedTime & CollectorOrganization) — PUT /Specimen/:id */
export async function specimenRujukanSampelWithReceivedtimeCollectororganization(
  client: SatuSehatClient, id: string, body: SpecimenRujukanSampelWithReceivedtimeCollectororganizationBody
): Promise<FhirResource> {
  return client.request("PUT", `/Specimen/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

/** Specimen - By ID — GET /Specimen/:id */
export async function specimenById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Specimen">> {
  return client.request("GET", `/Specimen/${id}`) as Promise<FhirResource<"Specimen">>;
}

export interface SpecimenSearchBySubjectParams {
    subject?: string | number;
    request?: string | number;
    collector?: string | number;
    collected?: string | number;
    identifier?: string | number;
}

/** Specimen - Search by Subject — GET /Specimen */
export async function specimenSearchBySubject(
  client: SatuSehatClient, params: SpecimenSearchBySubjectParams = {}
): Promise<FhirBundle<"Specimen">> {
  return client.request("GET", "/Specimen", {
    query: { subject: params.subject, request: params.request, collector: params.collector, collected: params.collected, identifier: params.identifier },
  }) as Promise<FhirBundle<"Specimen">>;
}

/** Specimen - PATCH — PATCH /Specimen/:id */
export async function specimenPatch(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Specimen/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
