/** Canonical CodeSystem URIs. The only place a system URI literal should appear. */
export const SYSTEM = {
  // HL7 standard (terminology.hl7.org)
  ACT_CODE: "http://terminology.hl7.org/CodeSystem/v3-ActCode",
  PARTICIPATION_TYPE: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
  ACT_REASON: "http://terminology.hl7.org/CodeSystem/v3-ActReason",
  GTS_ABBREVIATION: "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
  MARITAL_STATUS: "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
  OBSERVATION_INTERPRETATION: "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
  ROLE_CODE: "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
  ORDERABLE_DRUG_FORM: "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm",
  SUBSTANCE_ADMIN_SUBSTITUTION: "http://terminology.hl7.org/CodeSystem/v3-substanceAdminSubstitution",
  ADJUDICATION: "http://terminology.hl7.org/CodeSystem/adjudication",
  ALLERGYINTOLERANCE_CLINICAL: "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
  ALLERGYINTOLERANCE_VERIFICATION: "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
  BENEFIT_TYPE: "http://terminology.hl7.org/CodeSystem/benefit-type",
  CLAIM_TYPE: "http://terminology.hl7.org/CodeSystem/claim-type",
  COMMUNICATION_CATEGORY: "http://terminology.hl7.org/CodeSystem/communication-category",
  CONDITION_CATEGORY: "http://terminology.hl7.org/CodeSystem/condition-category",
  CONDITION_CLINICAL: "http://terminology.hl7.org/CodeSystem/condition-clinical",
  CONDITION_VERIFICATION_STATUS: "http://terminology.hl7.org/CodeSystem/condition-ver-status",
  CONTACT_ENTITY_TYPE: "http://terminology.hl7.org/CodeSystem/contactentity-type",
  COVERAGE_CLASS: "http://terminology.hl7.org/CodeSystem/coverage-class",
  COVERAGE_SELFPAY: "http://terminology.hl7.org/CodeSystem/coverage-selfpay",
  DATA_ABSENT_REASON: "http://terminology.hl7.org/CodeSystem/data-absent-reason",
  DIAGNOSIS_ROLE: "http://terminology.hl7.org/CodeSystem/diagnosis-role",
  DISCHARGE_DISPOSITION: "http://terminology.hl7.org/CodeSystem/discharge-disposition",
  DOSE_RATE_TYPE: "http://terminology.hl7.org/CodeSystem/dose-rate-type",
  EX_BENEFIT_CATEGORY: "http://terminology.hl7.org/CodeSystem/ex-benefitcategory",
  EX_DIAGNOSIS_TYPE: "http://terminology.hl7.org/CodeSystem/ex-diagnosistype",
  EX_PAYMENT_TYPE: "http://terminology.hl7.org/CodeSystem/ex-paymenttype",
  GOAL_ACHIEVEMENT: "http://terminology.hl7.org/CodeSystem/goal-achievement",
  GOAL_CATEGORY: "http://terminology.hl7.org/CodeSystem/goal-category",
  IMMUNIZATION_ORIGIN: "http://terminology.hl7.org/CodeSystem/immunization-origin",
  LOCATION_PHYSICAL_TYPE: "http://terminology.hl7.org/CodeSystem/location-physical-type",
  MEDICATION_ADMIN_CATEGORY: "http://terminology.hl7.org/CodeSystem/medication-admin-category",
  MEDICATION_STATEMENT_CATEGORY: "http://terminology.hl7.org/CodeSystem/medication-statement-category",
  // Really does carry a `/fhir/` segment — confirmed against a real working
  // MedicationDispense example (not a typo to "fix" to the canonical FHIR R4
  // form; SATU SEHAT's own reference examples consistently use this URL).
  MEDICATIONDISPENSE_CATEGORY: "http://terminology.hl7.org/fhir/CodeSystem/medicationdispense-category",
  MEDICATIONREQUEST_CATEGORY: "http://terminology.hl7.org/CodeSystem/medicationrequest-category",
  MEDICATIONREQUEST_COURSE_OF_THERAPY: "http://terminology.hl7.org/CodeSystem/medicationrequest-course-of-therapy",
  MEDICATIONREQUEST_STATUS_REASON: "http://terminology.hl7.org/CodeSystem/medicationrequest-status-reason",
  OBSERVATION_CATEGORY: "http://terminology.hl7.org/CodeSystem/observation-category",
  ORGANIZATION_TYPE: "http://terminology.hl7.org/CodeSystem/organization-type",
  PAYEE_TYPE: "http://terminology.hl7.org/CodeSystem/payeetype",
  PAYMENT_STATUS: "http://terminology.hl7.org/CodeSystem/payment-status",
  PAYMENT_TYPE: "http://terminology.hl7.org/CodeSystem/payment-type",
  PROCESS_PRIORITY: "http://terminology.hl7.org/CodeSystem/processpriority",
  REASON_MEDICATION_GIVEN: "http://terminology.hl7.org/CodeSystem/reason-medication-given",
  SERVICE_TYPE: "http://terminology.hl7.org/CodeSystem/service-type",
  SUBSCRIBER_RELATIONSHIP: "http://terminology.hl7.org/CodeSystem/subscriber-relationship",
  V2_0074: "http://terminology.hl7.org/CodeSystem/v2-0074",
  V2_0116: "http://terminology.hl7.org/CodeSystem/v2-0116",
  V2_0131: "http://terminology.hl7.org/CodeSystem/v2-0131",
  V2_0203: "http://terminology.hl7.org/CodeSystem/v2-0203",
  V2_0360: "http://terminology.hl7.org/CodeSystem/v2-0360",
  V2_0443: "http://terminology.hl7.org/CodeSystem/v2-0443",
  V2_0916: "http://terminology.hl7.org/CodeSystem/v2-0916",

  // Other international terminologies (free-text code spaces — no closed set)
  SNOMED: "http://snomed.info/sct",
  LOINC: "http://loinc.org",
  UCUM: "http://unitsofmeasure.org",
  ICD10: "http://hl7.org/fhir/sid/icd-10",
  ICD9CM: "http://hl7.org/fhir/sid/icd-9-cm",
  ATC: "http://www.whocc.no/atc",
  CVX: "http://hl7.org/fhir/sid/cvx",
  DICOM_DCM: "http://dicom.nema.org/resources/ontology/DCM",

  // Kemkes terminology server
  KEMKES_TERMINOLOGY_ROOT: "http://terminology.kemkes.go.id",
  KEMKES_CLINICAL_TERM: "http://terminology.kemkes.go.id/CodeSystem/clinical-term",
  KEMKES_KPTL: "http://terminology.kemkes.go.id/CodeSystem/kptl",
  KEMKES_MEDICATION_FORM: "http://terminology.kemkes.go.id/CodeSystem/medication-form",
  // Must be http, not https — confirmed against the live server, which
  // rejects https with "Invalid coding system" (RuleNumber: 10031). The
  // official doc page's own example shows https, which is simply wrong; the
  // server's validation error is the authoritative source here.
  KEMKES_MEDICATION_TYPE: "http://terminology.kemkes.go.id/CodeSystem/medication-type",
  KEMKES_COVERAGE_CLASS: "http://terminology.kemkes.go.id/CodeSystem/coverage-class",
  KEMKES_COVERAGE_TYPE: "http://terminology.kemkes.go.id/CodeSystem/coverage-type",
  KEMKES_CLAIM_INFORMATION_CATEGORY: "http://terminology.kemkes.go.id/CodeSystem/claiminformationcategory",
  KEMKES_CLAIM_RESPONSE_ADJUDICATION: "http://terminology.kemkes.go.id/CodeSystem/claimresponse-adjudication",
  KEMKES_CLINICAL_SPECIALITY: "http://terminology.kemkes.go.id/CodeSystem/clinical-speciality",
  KEMKES_CHARGE_ITEM_RESPONSE_STATUS: "http://terminology.kemkes.go.id/CodeSystem/chargeItemResponse-status",
  KEMKES_CHARGE_ITEM_BILLING_GROUP: "http://terminology.kemkes.go.id/CodeSystem/chargeItem-billingGroup",
  KEMKES_CHARGE_ITEM_TYPE: "http://terminology.kemkes.go.id/CodeSystem/chargeItem-type",
  KEMKES_CANCER_M_CATEGORY: "http://terminology.kemkes.go.id/CodeSystem/cancer-m-category",
  KEMKES_CANCER_N_CATEGORY: "http://terminology.kemkes.go.id/CodeSystem/cancer-n-category",
  KEMKES_CANCER_T_CATEGORY: "http://terminology.kemkes.go.id/CodeSystem/cancer-t-category",
  KEMKES_ICD_O_MORPHOLOGY: "http://terminology.kemkes.go.id/CodeSystem/icd-o-morphology",
  KEMKES_ICD_O_TOPOGRAPHY: "http://terminology.kemkes.go.id/CodeSystem/icd-o-topography",
  KEMKES_IMMUNIZATION_REASON: "http://terminology.kemkes.go.id/CodeSystem/immunization-reason",
  KEMKES_IMMUNIZATION_PROGRAM_ELIGIBILITY: "http://terminology.kemkes.go.id/CodeSystem/immunization-program-eligibility",
  KEMKES_IMMUNIZATION_ROUTINE_TIMING: "http://terminology.kemkes.go.id/CodeSystem/immunization-routine-timing",
  KEMKES_INACBG_V5: "http://terminology.kemkes.go.id/CodeSystem/inacbg-v5",
  KEMKES_INACBG_SAC_V5: "http://terminology.kemkes.go.id/CodeSystem/inacbg-sac-v5",
  KEMKES_INACBG_SPECIAL_CMG_V5: "http://terminology.kemkes.go.id/CodeSystem/inacbg-special-cmg-v5",
  KEMKES_KELUARGA_SEJAHTERA: "http://terminology.kemkes.go.id/CodeSystem/keluarga-sejahtera",
  KEMKES_LOCATION_TYPE: "http://terminology.kemkes.go.id/CodeSystem/location-type",
  KEMKES_LOCATION_SERVICE_CLASS_INPATIENT: "http://terminology.kemkes.go.id/CodeSystem/locationServiceClass-Inpatient",
  KEMKES_LOCATION_SERVICE_CLASS_OUTPATIENT: "http://terminology.kemkes.go.id/CodeSystem/locationServiceClass-Outpatient",
  KEMKES_LOCATION_UPGRADE_CLASS: "http://terminology.kemkes.go.id/CodeSystem/locationUpgradeClass",
  KEMKES_EPISODE_OF_CARE_TYPE: "http://terminology.kemkes.go.id/CodeSystem/episodeofcare-type",
  KEMKES_ORGANIZATION_TYPE: "http://terminology.kemkes.go.id/CodeSystem/organization-type",
  KEMKES_SMALLEST_LOGISTIC_UNIT: "http://terminology.kemkes.go.id/CodeSystem/smallest-logistic-unit",
  KEMKES_TARIFF_CLASS: "http://terminology.kemkes.go.id/CodeSystem/tariffClass",
  KEMKES_UPGRADE_CLASS_INDICATOR: "http://terminology.kemkes.go.id/CodeSystem/upgradeClassIndicator",
  KEMKES_V1_0201: "http://terminology.kemkes.go.id/v1-0201",
  KEMKES_V1_0302: "http://terminology.kemkes.go.id/v1-0302",

  // Kemkes sys-ids singleton namespaces (org-scoped ones go via identifiers.ts)
  ADMINISTRATIVE_AREA: "http://sys-ids.kemkes.go.id/administrative-area",
  KFA: "http://sys-ids.kemkes.go.id/kfa",
} as const;
