/**
 * gigi/anamnesis — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ConditionKeluhanUtamaBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
}

/** Condition - Keluhan Utama — POST /Condition */
export async function conditionKeluhanUtama(
  client: SatuSehatClient, body: ConditionKeluhanUtamaBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

export interface ObservationGolonganDarahBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  valueCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** Observation - Golongan Darah — POST /Observation */
export async function observationGolonganDarah(
  client: SatuSehatClient, body: ObservationGolonganDarahBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}

export interface AllergyintoleranceAlergiAspirinBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
    display?: string;
  };
}

/** AllergyIntolerance - Alergi Aspirin — POST /AllergyIntolerance */
export async function allergyintoleranceAlergiAspirin(
  client: SatuSehatClient, body: AllergyintoleranceAlergiAspirinBody
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("POST", "/AllergyIntolerance", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface MedicationdispenseSearchBySubjectParams {
    subject?: string | number;
}

/** MedicationDispense - Search by Subject — GET /MedicationDispense */
export async function medicationdispenseSearchBySubject(
  client: SatuSehatClient, params: MedicationdispenseSearchBySubjectParams = {}
): Promise<FhirBundle<"MedicationDispense">> {
  return client.request("GET", "/MedicationDispense", {
    query: { subject: params.subject },
  }) as Promise<FhirBundle<"MedicationDispense">>;
}

export interface MedicationstatementRiwayatPengobatanBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  dosage?: Array<Record<string, unknown>>;
  effectiveDateTime?: string;
  dateAsserted?: string;
  informationSource: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
}

/** MedicationStatement - Riwayat Pengobatan — POST /MedicationStatement */
export async function medicationstatementRiwayatPengobatan(
  client: SatuSehatClient, body: MedicationstatementRiwayatPengobatanBody
): Promise<unknown> {
  return client.request("POST", "/MedicationStatement", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}
