/**
 * gigi/diagnosis — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ConditionDiagnosisAwalMasukBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  bodySite?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  onsetDateTime?: string;
  recordedDate?: string;
  note?: Array<Record<string, unknown>>;
}

/** Condition - Diagnosis Awal/ Masuk — POST /Condition */
export async function conditionDiagnosisAwalMasuk(
  client: SatuSehatClient, body: ConditionDiagnosisAwalMasukBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}
