/**
 * gigi/pemeriksaan-fisik — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ObservationNadiBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  valueQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  interpretation?: Array<Record<string, unknown>>;
  bodySite: {
    coding?: Array<Record<string, unknown>>;
  };
  valueCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** Observation - Nadi — POST /Observation */
export async function observationNadi(
  client: SatuSehatClient, body: ObservationNadiBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}
