/**
 * gigi/pemeriksaan-penunjang — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ProcedureCreateStatusPuasaBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** Procedure - Create - Status Puasa — POST /Procedure */
export async function procedureCreateStatusPuasa(
  client: SatuSehatClient, body: ProcedureCreateStatusPuasaBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}

export interface ServicerequestCreatePermintaanPemeriksaanLaboratoriumBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  orderDetail?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  occurrenceDateTime?: string;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
  reasonReference?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
  supportingInfo?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
}

/** ServiceRequest - Create - Permintaan Pemeriksaan Laboratorium — POST /ServiceRequest */
export async function servicerequestCreatePermintaanPemeriksaanLaboratorium(
  client: SatuSehatClient, body: ServicerequestCreatePermintaanPemeriksaanLaboratoriumBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}

export interface SpecimenCreateDataSpesimenBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  collection: {
    method: {
      coding?: Array<Record<string, unknown>>;
    };
    collectedDateTime?: string;
    quantity: {
      value?: number;
      unit?: string;
    };
    collector: {
      reference?: string;
      display?: string;
    };
    fastingStatusCodeableConcept: {
      coding?: Array<Record<string, unknown>>;
    };
  };
  processing?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
    display?: string;
  };
  request?: Array<Record<string, unknown>>;
  receivedTime?: string;
  extension?: Array<Record<string, unknown>>;
}

/** Specimen - Create - Data Spesimen — POST /Specimen */
export async function specimenCreateDataSpesimen(
  client: SatuSehatClient, body: SpecimenCreateDataSpesimenBody
): Promise<FhirResource<"Specimen">> {
  return client.request("POST", "/Specimen", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Specimen">>;
}

export interface ObservationCreateHasilPemeriksaanHemoglobinBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  bodySite: {
    coding?: Array<Record<string, unknown>>;
  };
  derivedFrom?: Array<Record<string, unknown>>;
  valueString?: string;
  specimen: {
    reference?: string;
  };
  valueQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  interpretation?: Array<Record<string, unknown>>;
  referenceRange?: Array<Record<string, unknown>>;
}

/** Observation - Create - Hasil Pemeriksaan Hemoglobin — POST /Observation */
export async function observationCreateHasilPemeriksaanHemoglobin(
  client: SatuSehatClient, body: ObservationCreateHasilPemeriksaanHemoglobinBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}

export interface DiagnosticreportCreateDataLaporanHasilPemeriksaanLaboratoriumBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  imagingStudy?: Array<Record<string, unknown>>;
  result?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  conclusion?: string;
  specimen?: Array<Record<string, unknown>>;
}

/** DiagnosticReport - Create - Data Laporan Hasil Pemeriksaan Laboratorium — POST /DiagnosticReport */
export async function diagnosticreportCreateDataLaporanHasilPemeriksaanLaboratorium(
  client: SatuSehatClient, body: DiagnosticreportCreateDataLaporanHasilPemeriksaanLaboratoriumBody
): Promise<FhirResource<"DiagnosticReport">> {
  return client.request("POST", "/DiagnosticReport", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"DiagnosticReport">>;
}

export interface AllergyintoleranceCreateStatusAlergiTerhadapBahanKontrasBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
  };
}

/** AllergyIntolerance - Create - Status Alergi terhadap Bahan Kontras — POST /AllergyIntolerance */
export async function allergyintoleranceCreateStatusAlergiTerhadapBahanKontras(
  client: SatuSehatClient, body: AllergyintoleranceCreateStatusAlergiTerhadapBahanKontrasBody
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("POST", "/AllergyIntolerance", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface ImagingstudyGetIdBasedOnAccessionNumberParams {
    identifier?: string | number;
}

/** ImagingStudy - Get ID based on Accession Number — GET /ImagingStudy */
export async function imagingstudyGetIdBasedOnAccessionNumber(
  client: SatuSehatClient, params: ImagingstudyGetIdBasedOnAccessionNumberParams = {}
): Promise<FhirBundle<"ImagingStudy">> {
  return client.request("GET", "/ImagingStudy", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"ImagingStudy">>;
}
