/**
 * gigi/pendaftaran-kunjungan-rawat-jalan-gigi — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface EncounterMasukKunjunganBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  location?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  serviceProvider: {
    reference?: string;
  };
}

/** Encounter - Masuk Kunjungan — POST /Encounter */
export async function encounterMasukKunjungan(
  client: SatuSehatClient, body: EncounterMasukKunjunganBody
): Promise<FhirResource<"Encounter">> {
  return client.request("POST", "/Encounter", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Encounter">>;
}

export interface EncounterMasukRuangBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  location?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  serviceProvider: {
    reference?: string;
  };
}

/** Encounter - Masuk ruang — PUT /Encounter/:id */
export async function encounterMasukRuang(
  client: SatuSehatClient, id: string, body: EncounterMasukRuangBody
): Promise<FhirResource> {
  return client.request("PUT", `/Encounter/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}
