/**
 * gigi/tatalaksana — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ProcedureDiberikanEdukasiBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** Procedure - Diberikan Edukasi — POST /Procedure */
export async function procedureDiberikanEdukasi(
  client: SatuSehatClient, body: ProcedureDiberikanEdukasiBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}

export interface MedicationCreateForRequestBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  status?: string;
  manufacturer: {
    reference?: string;
  };
  form: {
    coding?: Array<Record<string, unknown>>;
  };
  batch: {
    lotNumber?: string;
    expirationDate?: string;
  };
  ingredient?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** Medication - Create (for Request) — POST /Medication */
export async function medicationCreateForRequest(
  client: SatuSehatClient, body: MedicationCreateForRequestBody
): Promise<FhirResource<"Medication">> {
  return client.request("POST", "/Medication", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Medication">>;
}

export interface MedicationrequestCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  priority?: string;
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  dosageInstruction?: Array<Record<string, unknown>>;
  dispenseRequest: {
    dispenseInterval: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    validityPeriod: {
      start?: string;
      end?: string;
    };
    numberOfRepeatsAllowed?: number;
    quantity: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    expectedSupplyDuration: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    performer: {
      reference?: string;
    };
  };
}

/** MedicationRequest - Create — POST /MedicationRequest */
export async function medicationrequestCreate(
  client: SatuSehatClient, body: MedicationrequestCreateBody
): Promise<FhirResource<"MedicationRequest">> {
  return client.request("POST", "/MedicationRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationRequest">>;
}

export interface QuestionnaireresponsePengkajianResepBody {
  resourceType?: string;
  questionnaire?: string;
  status?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authored?: string;
  author: {
    reference?: string;
    display?: string;
  };
  source: {
    reference?: string;
  };
  item?: Array<Record<string, unknown>>;
}

/** QuestionnaireResponse - Pengkajian Resep — POST /QuestionnaireResponse */
export async function questionnaireresponsePengkajianResep(
  client: SatuSehatClient, body: QuestionnaireresponsePengkajianResepBody
): Promise<FhirResource<"QuestionnaireResponse">> {
  return client.request("POST", "/QuestionnaireResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"QuestionnaireResponse">>;
}

export interface MedicationdispenseCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  authorizingPrescription?: Array<Record<string, unknown>>;
  quantity: {
    system?: string;
    code?: string;
    value?: number;
  };
  daysSupply: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  whenPrepared?: string;
  whenHandedOver?: string;
  dosageInstruction?: Array<Record<string, unknown>>;
}

/** MedicationDispense - Create — POST /MedicationDispense */
export async function medicationdispenseCreate(
  client: SatuSehatClient, body: MedicationdispenseCreateBody
): Promise<FhirResource<"MedicationDispense">> {
  return client.request("POST", "/MedicationDispense", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationDispense">>;
}
