/**
 * gigi/tindakan — generated by scripts/generate-modules.mjs
 * from "24. Use Case - Gigi.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ProcedureTindakanScalingBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** Procedure - Tindakan Scaling — POST /Procedure */
export async function procedureTindakanScaling(
  client: SatuSehatClient, body: ProcedureTindakanScalingBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}
