/**
 * klaim-bpjs/contoh-klaim — generated by scripts/generate-modules.mjs
 * from "26. Use Case - Modul Klaim (BPJS-K).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

// Search/create/lookup already implemented once in src/common/*.ts.
export { createOrganization, createLocation } from "../common/organization.js";
export { searchPatient, getPatientById, searchPractitioner, getPractitionerById } from "../common/search.js";

export interface CoverageKepesertaanBpjsKBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - BPJS-K — POST /Coverage */
export async function coverageKepesertaanBpjsK(
  client: SatuSehatClient, body: CoverageKepesertaanBpjsKBody
): Promise<FhirResource<"Coverage">> {
  return client.request("POST", "/Coverage", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Coverage">>;
}

export interface CoverageMendapatkanDataKepesertaanParams {
    patient?: string | number;
    identifier?: string | number;
}

/** Coverage - Mendapatkan Data Kepesertaan — GET /Coverage */
export async function coverageMendapatkanDataKepesertaan(
  client: SatuSehatClient, params: CoverageMendapatkanDataKepesertaanParams = {}
): Promise<FhirBundle<"Coverage">> {
  return client.request("GET", "/Coverage", {
    query: { patient: params.patient, identifier: params.identifier },
  }) as Promise<FhirBundle<"Coverage">>;
}

/** CoverageEligibilityResponse - Response SEP — POST /CoverageEligibilityResponse */
export async function coverageeligibilityresponseResponseSep(
  client: SatuSehatClient
): Promise<FhirResource<"CoverageEligibilityResponse">> {
  return client.request("POST", "/CoverageEligibilityResponse") as Promise<FhirResource<"CoverageEligibilityResponse">>;
}

export interface EncounterKunjunganBaruBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  location?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  serviceProvider: {
    reference?: string;
  };
  basedOn?: Array<Record<string, unknown>>;
  serviceType: {
    coding?: Array<Record<string, unknown>>;
  };
  extension?: Array<Record<string, unknown>>;
}

/** Encounter - Kunjungan Baru — POST /Encounter */
export async function encounterKunjunganBaru(
  client: SatuSehatClient, body: EncounterKunjunganBaruBody
): Promise<FhirResource<"Encounter">> {
  return client.request("POST", "/Encounter", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Encounter">>;
}

export interface EncounterMasukRuangBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  serviceType: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  length: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  location?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  hospitalization: {
    dischargeDisposition: {
      coding?: Array<Record<string, unknown>>;
      text?: string;
    };
  };
  serviceProvider: {
    reference?: string;
  };
  basedOn?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
  account?: Array<Record<string, unknown>>;
}

/** Encounter - Masuk Ruang — PUT /Encounter/:id */
export async function encounterMasukRuang(
  client: SatuSehatClient, id: string, body: EncounterMasukRuangBody
): Promise<FhirResource> {
  return client.request("PUT", `/Encounter/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

export interface AccountBody {
  resourceType?: string;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  name?: string;
  subject?: Array<Record<string, unknown>>;
  servicePeriod: {
    start?: string;
    end?: string;
  };
  coverage?: Array<Record<string, unknown>>;
  owner: {
    reference?: string;
  };
  description?: string;
}

/** Account — POST /Account */
export async function account(
  client: SatuSehatClient, body: AccountBody
): Promise<FhirResource<"Account">> {
  return client.request("POST", "/Account", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Account">>;
}

/** Encounter - Account — PATCH /Encounter/:id */
export async function encounterAccount(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Encounter/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface ConditionKeluhanUtamaBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  onsetDateTime?: string;
  recordedDate?: string;
  recorder: {
    reference?: string;
    display?: string;
  };
  note?: Array<Record<string, unknown>>;
  stage?: Array<Record<string, unknown>>;
  onsetAge: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  onsetPeriod: {
    start?: string;
    end?: string;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** Condition  - Keluhan Utama — POST /Condition */
export async function conditionKeluhanUtama(
  client: SatuSehatClient, body: ConditionKeluhanUtamaBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

export interface FamilymemberhistoryRiwayatPenyakitKeluargaBody {
  resourceType?: string;
  status?: string;
  relationship: {
    coding?: Array<Record<string, unknown>>;
  };
  deceasedBoolean?: boolean;
  patient: {
    reference?: string;
    display?: string;
  };
  date?: string;
  condition?: Array<Record<string, unknown>>;
}

/** FamilyMemberHistory - Riwayat Penyakit Keluarga — POST /FamilyMemberHistory */
export async function familymemberhistoryRiwayatPenyakitKeluarga(
  client: SatuSehatClient, body: FamilymemberhistoryRiwayatPenyakitKeluargaBody
): Promise<unknown> {
  return client.request("POST", "/FamilyMemberHistory", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface AlergiLingkunganDebuRumahBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
    display?: string;
  };
}

/** Alergi Lingkungan - Debu Rumah — POST /AllergyIntolerance */
export async function alergiLingkunganDebuRumah(
  client: SatuSehatClient, body: AlergiLingkunganDebuRumahBody
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("POST", "/AllergyIntolerance", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface MedicationdispenseSearchBySubjectParams {
    subject?: string | number;
}

/** MedicationDispense - Search by Subject — GET /MedicationDispense */
export async function medicationdispenseSearchBySubject(
  client: SatuSehatClient, params: MedicationdispenseSearchBySubjectParams = {}
): Promise<FhirBundle<"MedicationDispense">> {
  return client.request("GET", "/MedicationDispense", {
    query: { subject: params.subject },
  }) as Promise<FhirBundle<"MedicationDispense">>;
}

export interface MedicationstatementRiwayatPengobatanObatDariFasyankesSendiriBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  dosage?: Array<Record<string, unknown>>;
  effectiveDateTime?: string;
  dateAsserted?: string;
  informationSource: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  medicationCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** MedicationStatement - Riwayat Pengobatan (Obat dari Fasyankes Sendiri) — POST /MedicationStatement */
export async function medicationstatementRiwayatPengobatanObatDariFasyankesSendiri(
  client: SatuSehatClient, body: MedicationstatementRiwayatPengobatanObatDariFasyankesSendiriBody
): Promise<unknown> {
  return client.request("POST", "/MedicationStatement", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface ObservationTdSistolikBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  valueCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
  basedOn?: Array<Record<string, unknown>>;
  partOf?: Array<Record<string, unknown>>;
  component?: Array<Record<string, unknown>>;
  valueString?: string;
  identifier?: Array<Record<string, unknown>>;
  bodySite: {
    coding?: Array<Record<string, unknown>>;
  };
  derivedFrom?: Array<Record<string, unknown>>;
  specimen: {
    reference?: string;
  };
  valueQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  interpretation?: Array<Record<string, unknown>>;
  referenceRange?: Array<Record<string, unknown>>;
  valueBoolean?: boolean;
  hasMember?: Array<Record<string, unknown>>;
  valueInteger?: number;
}

/** Observation - TD Sistolik — POST /Observation */
export async function observationTdSistolik(
  client: SatuSehatClient, body: ObservationTdSistolikBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}

export interface ClinicalimpressionRiwayatPerjalananPenyakitBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  date?: string;
  assessor: {
    reference?: string;
  };
  problem?: Array<Record<string, unknown>>;
  investigation?: Array<Record<string, unknown>>;
  summary?: string;
  finding?: Array<Record<string, unknown>>;
  prognosisCodeableConcept?: Array<Record<string, unknown>>;
}

/** ClinicalImpression - Riwayat Perjalanan Penyakit — POST /ClinicalImpression */
export async function clinicalimpressionRiwayatPerjalananPenyakit(
  client: SatuSehatClient, body: ClinicalimpressionRiwayatPerjalananPenyakitBody
): Promise<FhirResource<"ClinicalImpression">> {
  return client.request("POST", "/ClinicalImpression", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClinicalImpression">>;
}

export interface GoalCreateTujuanPerawatanBody {
  resourceType?: string;
  lifecycleStatus?: string;
  category?: Array<Record<string, unknown>>;
  description: {
    text?: string;
  };
  subject: {
    reference?: string;
  };
  target?: Array<Record<string, unknown>>;
  statusDate?: string;
  expressedBy: {
    reference?: string;
  };
  addresses?: Array<Record<string, unknown>>;
}

/** Goal - Create - Tujuan Perawatan — POST /Goal */
export async function goalCreateTujuanPerawatan(
  client: SatuSehatClient, body: GoalCreateTujuanPerawatanBody
): Promise<unknown> {
  return client.request("POST", "/Goal", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface GoalUpdateTujuanPerawatanBody {
  resourceType?: string;
  id?: string;
  lifecycleStatus?: string;
  achievementStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  description: {
    text?: string;
  };
  subject: {
    reference?: string;
  };
  target?: Array<Record<string, unknown>>;
  statusDate?: string;
  expressedBy: {
    reference?: string;
  };
  addresses?: Array<Record<string, unknown>>;
  outcomeCode?: Array<Record<string, unknown>>;
}

/** Goal - Update - Tujuan Perawatan — PUT /Goal/:id */
export async function goalUpdateTujuanPerawatan(
  client: SatuSehatClient, id: string, body: GoalUpdateTujuanPerawatanBody
): Promise<unknown> {
  return client.request("PUT", `/Goal/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface CareplanRencanaRawatPasienBody {
  resourceType?: string;
  title?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  intent?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  created?: string;
  author: {
    reference?: string;
    display?: string;
  };
  goal?: Array<Record<string, unknown>>;
}

/** CarePlan - Rencana Rawat Pasien — POST /CarePlan */
export async function careplanRencanaRawatPasien(
  client: SatuSehatClient, body: CareplanRencanaRawatPasienBody
): Promise<FhirResource<"CarePlan">> {
  return client.request("POST", "/CarePlan", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CarePlan">>;
}

export interface ProcedureStatusPuasaCreateBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  usedCode?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
}

/** Procedure Status Puasa  - Create — POST /Procedure */
export async function procedureStatusPuasaCreate(
  client: SatuSehatClient, body: ProcedureStatusPuasaCreateBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}

export interface ServicerequestCreateBody {
  resourceType?: string;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  reasonCode?: Array<Record<string, unknown>>;
  reasonReference?: Array<Record<string, unknown>>;
  orderDetail?: Array<Record<string, unknown>>;
  occurrencePeriod: {
    start?: string;
  };
  note?: Array<Record<string, unknown>>;
  supportingInfo?: Array<Record<string, unknown>>;
  identifier?: Array<Record<string, unknown>>;
  priority?: string;
  occurrenceDateTime?: string;
  locationReference?: Array<Record<string, unknown>>;
  patientInstruction?: string;
  locationCode?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
}

/** ServiceRequest - Create — POST /ServiceRequest */
export async function servicerequestCreate(
  client: SatuSehatClient, body: ServicerequestCreateBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}

export interface SpecimenCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  condition?: Array<Record<string, unknown>>;
  collection: {
    collector: {
      reference?: string;
      display?: string;
    };
    collectedDateTime?: string;
    quantity: {
      value?: number;
      code?: string;
      unit?: string;
      system?: string;
    };
    method: {
      coding?: Array<Record<string, unknown>>;
    };
    bodySite: {
      coding?: Array<Record<string, unknown>>;
    };
    fastingStatusCodeableConcept: {
      coding?: Array<Record<string, unknown>>;
    };
  };
  subject: {
    reference?: string;
    display?: string;
  };
  request?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
  receivedTime?: string;
  processing?: Array<Record<string, unknown>>;
}

/** Specimen - Create — POST /Specimen */
export async function specimenCreate(
  client: SatuSehatClient, body: SpecimenCreateBody
): Promise<FhirResource<"Specimen">> {
  return client.request("POST", "/Specimen", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Specimen">>;
}

export interface DiagnosticreportGolonganDarahACreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  imagingStudy?: Array<Record<string, unknown>>;
  result?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  conclusion?: string;
  specimen?: Array<Record<string, unknown>>;
  conclusionCode?: Array<Record<string, unknown>>;
}

/** DiagnosticReport Golongan Darah A - Create — POST /DiagnosticReport */
export async function diagnosticreportGolonganDarahACreate(
  client: SatuSehatClient, body: DiagnosticreportGolonganDarahACreateBody
): Promise<FhirResource<"DiagnosticReport">> {
  return client.request("POST", "/DiagnosticReport", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"DiagnosticReport">>;
}

export interface ImagingstudyGetIdBasedOnAccessionNumberParams {
    identifier?: string | number;
}

/** ImagingStudy - Get ID based on Accession Number — GET /ImagingStudy */
export async function imagingstudyGetIdBasedOnAccessionNumber(
  client: SatuSehatClient, params: ImagingstudyGetIdBasedOnAccessionNumberParams = {}
): Promise<FhirBundle<"ImagingStudy">> {
  return client.request("GET", "/ImagingStudy", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"ImagingStudy">>;
}

/** ClinicalImpression - PATCH Rasional Klinis — PATCH /ClinicalImpression/:id */
export async function clinicalimpressionPatchRasionalKlinis(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/ClinicalImpression/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface RiskassessmentPenilaianRisikoBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  performer: {
    reference?: string;
  };
  condition: {
    reference?: string;
  };
  reasonReference?: Array<Record<string, unknown>>;
  prediction?: Array<Record<string, unknown>>;
  mitigation?: string;
}

/** RiskAssessment - Penilaian Risiko — POST /RiskAssessment */
export async function riskassessmentPenilaianRisiko(
  client: SatuSehatClient, body: RiskassessmentPenilaianRisikoBody
): Promise<unknown> {
  return client.request("POST", "/RiskAssessment", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface CompositionLaporanOperasiBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  date?: string;
  title?: string;
  author?: Array<Record<string, unknown>>;
  custodian: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  section?: Array<Record<string, unknown>>;
  attester?: Array<Record<string, unknown>>;
  event?: Array<Record<string, unknown>>;
  identifier: {
    system?: string;
    value?: string;
  };
}

/** Composition - Laporan Operasi — POST /Composition */
export async function compositionLaporanOperasi(
  client: SatuSehatClient, body: CompositionLaporanOperasiBody
): Promise<FhirResource<"Composition">> {
  return client.request("POST", "/Composition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Composition">>;
}

export interface MedicationCreateBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  status?: string;
  manufacturer: {
    reference?: string;
  };
  form: {
    coding?: Array<Record<string, unknown>>;
  };
  ingredient?: Array<Record<string, unknown>>;
  batch: {
    lotNumber?: string;
    expirationDate?: string;
  };
  extension?: Array<Record<string, unknown>>;
}

/** Medication - Create — POST /Medication */
export async function medicationCreate(
  client: SatuSehatClient, body: MedicationCreateBody
): Promise<FhirResource<"Medication">> {
  return client.request("POST", "/Medication", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Medication">>;
}

export interface MedicationrequestCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  priority?: string;
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  reasonReference?: Array<Record<string, unknown>>;
  courseOfTherapyType: {
    coding?: Array<Record<string, unknown>>;
  };
  dosageInstruction?: Array<Record<string, unknown>>;
  dispenseRequest: {
    dispenseInterval: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    validityPeriod: {
      start?: string;
      end?: string;
    };
    numberOfRepeatsAllowed?: number;
    quantity: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    expectedSupplyDuration: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    performer: {
      reference?: string;
    };
  };
}

/** MedicationRequest - Create — POST /MedicationRequest */
export async function medicationrequestCreate(
  client: SatuSehatClient, body: MedicationrequestCreateBody
): Promise<FhirResource<"MedicationRequest">> {
  return client.request("POST", "/MedicationRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationRequest">>;
}

export interface QuestionnaireresponsePengkajianResepBody {
  resourceType?: string;
  questionnaire?: string;
  status?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authored?: string;
  author: {
    reference?: string;
    display?: string;
  };
  source: {
    reference?: string;
  };
  item?: Array<Record<string, unknown>>;
  identifier: {
    system?: string;
    value?: string;
  };
}

/** QuestionnaireResponse - Pengkajian Resep — POST /QuestionnaireResponse */
export async function questionnaireresponsePengkajianResep(
  client: SatuSehatClient, body: QuestionnaireresponsePengkajianResepBody
): Promise<FhirResource<"QuestionnaireResponse">> {
  return client.request("POST", "/QuestionnaireResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"QuestionnaireResponse">>;
}

export interface MedicationdispenseCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  authorizingPrescription?: Array<Record<string, unknown>>;
  quantity: {
    system?: string;
    code?: string;
    value?: number;
  };
  daysSupply: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  whenPrepared?: string;
  whenHandedOver?: string;
  dosageInstruction?: Array<Record<string, unknown>>;
}

/** MedicationDispense - Create — POST /MedicationDispense */
export async function medicationdispenseCreate(
  client: SatuSehatClient, body: MedicationdispenseCreateBody
): Promise<FhirResource<"MedicationDispense">> {
  return client.request("POST", "/MedicationDispense", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationDispense">>;
}

export interface MedicationadministrationCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  effectivePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  request: {
    reference?: string;
  };
  dosage: {
    site: {
      coding?: Array<Record<string, unknown>>;
    };
    route: {
      coding?: Array<Record<string, unknown>>;
    };
    dose: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
  };
}

/** MedicationAdministration - Create — POST /MedicationAdministration */
export async function medicationadministrationCreate(
  client: SatuSehatClient, body: MedicationadministrationCreateBody
): Promise<unknown> {
  return client.request("POST", "/MedicationAdministration", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface NutritionorderDietBody {
  resourceType?: string;
  status?: string;
  intent?: string;
  patient: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  dateTime?: string;
  orderer: {
    reference?: string;
  };
  excludeFoodModifier?: Array<Record<string, unknown>>;
  oralDiet: {
    type?: Array<Record<string, unknown>>;
    nutrient?: Array<Record<string, unknown>>;
  };
}

/** NutritionOrder - Diet — POST /NutritionOrder */
export async function nutritionorderDiet(
  client: SatuSehatClient, body: NutritionorderDietBody
): Promise<unknown> {
  return client.request("POST", "/NutritionOrder", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface DeviceAlkesBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  manufacturer?: string;
  deviceName?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  lotNumber?: string;
  serialNumber?: string;
  owner: {
    reference?: string;
  };
}

/** Device - Alkes — POST /Device */
export async function deviceAlkes(
  client: SatuSehatClient, body: DeviceAlkesBody
): Promise<unknown> {
  return client.request("POST", "/Device", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface DevicerequestPermintaanAlkesBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  codeReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
  };
  performer: {
    reference?: string;
  };
  reasonCode?: Array<Record<string, unknown>>;
}

/** DeviceRequest - Permintaan Alkes — POST /DeviceRequest */
export async function devicerequestPermintaanAlkes(
  client: SatuSehatClient, body: DevicerequestPermintaanAlkesBody
): Promise<unknown> {
  return client.request("POST", "/DeviceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface DevicedispensePengeluaranAlkesBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  basedOn?: Array<Record<string, unknown>>;
  device: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
  };
  receiver: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  whenPrepared?: string;
  whenHandedOver?: string;
  destination: {
    reference?: string;
  };
  note?: Array<Record<string, unknown>>;
}

/** DeviceDispense - Pengeluaran Alkes — POST /DeviceDispense */
export async function devicedispensePengeluaranAlkes(
  client: SatuSehatClient, body: DevicedispensePengeluaranAlkesBody
): Promise<unknown> {
  return client.request("POST", "/DeviceDispense", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface DeviceusestatementPenggunaanAlkesBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  device: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
  };
  timingPeriod: {
    start?: string;
    end?: string;
  };
  recordedOn?: string;
  source: {
    reference?: string;
  };
  reasonCode?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** DeviceUseStatement - Penggunaan Alkes — POST /DeviceUseStatement */
export async function deviceusestatementPenggunaanAlkes(
  client: SatuSehatClient, body: DeviceusestatementPenggunaanAlkesBody
): Promise<unknown> {
  return client.request("POST", "/DeviceUseStatement", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface SupplyrequestPermintaanStokBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  itemReference: {
    reference?: string;
    display?: string;
  };
  quantity: {
    value?: number;
    unit?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  supplier?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
}

/** SupplyRequest - Permintaan Stok — POST /SupplyRequest */
export async function supplyrequestPermintaanStok(
  client: SatuSehatClient, body: SupplyrequestPermintaanStokBody
): Promise<unknown> {
  return client.request("POST", "/SupplyRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface SupplydeliveryPengirimanStokBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  status?: string;
  patient: {
    reference?: string;
  };
  suppliedItem: {
    itemReference: {
      reference?: string;
      display?: string;
    };
    quantity: {
      value?: number;
      unit?: string;
    };
  };
  occurrenceDateTime?: string;
  supplier: {
    reference?: string;
    display?: string;
  };
  destination: {
    reference?: string;
  };
  receiver?: Array<Record<string, unknown>>;
}

/** SupplyDelivery - Pengiriman Stok — POST /SupplyDelivery */
export async function supplydeliveryPengirimanStok(
  client: SatuSehatClient, body: SupplydeliveryPengirimanStokBody
): Promise<unknown> {
  return client.request("POST", "/SupplyDelivery", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface ChargeitemHematologiRutinBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  occurrencePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  quantity: {
    value?: number;
  };
  account?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** ChargeItem - Hematologi Rutin — POST /ChargeItem */
export async function chargeitemHematologiRutin(
  client: SatuSehatClient, body: ChargeitemHematologiRutinBody
): Promise<FhirResource<"ChargeItem">> {
  return client.request("POST", "/ChargeItem", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ChargeItem">>;
}

export interface InvoiceInvoiceBody {
  resourceType?: string;
  status?: string;
  subject: {
    reference?: string;
  };
  date?: string;
  issuer: {
    reference?: string;
  };
  account: {
    reference?: string;
  };
  lineItem?: Array<Record<string, unknown>>;
  totalNet: {
    value?: number;
    currency?: string;
  };
}

/** Invoice - Invoice — POST /Invoice */
export async function invoiceInvoice(
  client: SatuSehatClient, body: InvoiceInvoiceBody
): Promise<FhirResource<"Invoice">> {
  return client.request("POST", "/Invoice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Invoice">>;
}

/** Location - Bed 2 jika path operationalStatus belum ada — PATCH /Location/:id */
export async function locationBed2JikaPathOperationalstatusBelumAda(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Location/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface PatientCreateByNikBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  active?: boolean;
  name?: Array<Record<string, unknown>>;
  telecom?: Array<Record<string, unknown>>;
  gender?: string;
  birthDate?: string;
  deceasedBoolean?: boolean;
  address?: Array<Record<string, unknown>>;
  maritalStatus: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  multipleBirthInteger?: number;
  contact?: Array<Record<string, unknown>>;
  communication?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** Patient - Create by NIK — POST /Patient */
export async function patientCreateByNik(
  client: SatuSehatClient, body: PatientCreateByNikBody
): Promise<FhirResource<"Patient">> {
  return client.request("POST", "/Patient", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Patient">>;
}
