/**
 * klaim-bpjs/variabel — generated by scripts/generate-modules.mjs
 * from "26. Use Case - Modul Klaim (BPJS-K).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CoverageKepesertaanBpjsKBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - BPJS-K — POST /Coverage */
export async function coverageKepesertaanBpjsK(
  client: SatuSehatClient, body: CoverageKepesertaanBpjsKBody
): Promise<FhirResource<"Coverage">> {
  return client.request("POST", "/Coverage", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Coverage">>;
}

export interface CoverageMendapatkanDataKepesertaanParams {
    patient?: string | number;
    identifier?: string | number;
}

/** Coverage - Mendapatkan Data Kepesertaan — GET /Coverage */
export async function coverageMendapatkanDataKepesertaan(
  client: SatuSehatClient, params: CoverageMendapatkanDataKepesertaanParams = {}
): Promise<FhirBundle<"Coverage">> {
  return client.request("GET", "/Coverage", {
    query: { patient: params.patient, identifier: params.identifier },
  }) as Promise<FhirBundle<"Coverage">>;
}

/** CoverageEligibilityResponse - Response SEP — POST /CoverageEligibilityResponse */
export async function coverageeligibilityresponseResponseSep(
  client: SatuSehatClient
): Promise<FhirResource<"CoverageEligibilityResponse">> {
  return client.request("POST", "/CoverageEligibilityResponse") as Promise<FhirResource<"CoverageEligibilityResponse">>;
}

export interface AccountBody {
  resourceType?: string;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  name?: string;
  subject?: Array<Record<string, unknown>>;
  servicePeriod: {
    start?: string;
    end?: string;
  };
  coverage?: Array<Record<string, unknown>>;
  owner: {
    reference?: string;
  };
  description?: string;
}

/** Account — POST /Account */
export async function account(
  client: SatuSehatClient, body: AccountBody
): Promise<FhirResource<"Account">> {
  return client.request("POST", "/Account", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Account">>;
}

/** Encounter - Account — PATCH /Encounter/:id */
export async function encounterAccount(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Encounter/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface ChargeitemHematologiRutinBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  occurrencePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  quantity: {
    value?: number;
  };
  account?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** ChargeItem - Hematologi Rutin — POST /ChargeItem */
export async function chargeitemHematologiRutin(
  client: SatuSehatClient, body: ChargeitemHematologiRutinBody
): Promise<FhirResource<"ChargeItem">> {
  return client.request("POST", "/ChargeItem", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ChargeItem">>;
}

export interface InvoiceInvoiceDrgBody {
  resourceType?: string;
  status?: string;
  subject: {
    reference?: string;
  };
  date?: string;
  issuer: {
    reference?: string;
  };
  account: {
    reference?: string;
  };
  lineItem?: Array<Record<string, unknown>>;
  totalNet: {
    value?: number;
    currency?: string;
  };
}

/** Invoice - Invoice (DRG) — POST /Invoice */
export async function invoiceInvoiceDrg(
  client: SatuSehatClient, body: InvoiceInvoiceDrgBody
): Promise<FhirResource<"Invoice">> {
  return client.request("POST", "/Invoice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Invoice">>;
}
