/**
 * rawat-jalan/anamnesis — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ConditionKeluhanUtamaBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  onsetAge: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
    display?: string;
  };
  note?: Array<Record<string, unknown>>;
  onsetPeriod: {
    start?: string;
    end?: string;
  };
  onsetDateTime?: string;
}

/** Condition  - Keluhan Utama — POST /Condition */
export async function conditionKeluhanUtama(
  client: SatuSehatClient, body: ConditionKeluhanUtamaBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

export interface FamilymemberhistoryRiwayatPenyakitKeluargaBody {
  resourceType?: string;
  status?: string;
  relationship: {
    coding?: Array<Record<string, unknown>>;
  };
  deceasedBoolean?: boolean;
  patient: {
    reference?: string;
    display?: string;
  };
  date?: string;
  condition?: Array<Record<string, unknown>>;
}

/** FamilyMemberHistory - Riwayat Penyakit Keluarga — POST /FamilyMemberHistory */
export async function familymemberhistoryRiwayatPenyakitKeluarga(
  client: SatuSehatClient, body: FamilymemberhistoryRiwayatPenyakitKeluargaBody
): Promise<unknown> {
  return client.request("POST", "/FamilyMemberHistory", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface AlergiLingkunganDebuRumahBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
    display?: string;
  };
}

/** Alergi Lingkungan - Debu Rumah — POST /AllergyIntolerance */
export async function alergiLingkunganDebuRumah(
  client: SatuSehatClient, body: AlergiLingkunganDebuRumahBody
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("POST", "/AllergyIntolerance", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface MedicationdispenseSearchBySubjectParams {
    subject?: string | number;
}

/** MedicationDispense - Search by Subject — GET /MedicationDispense */
export async function medicationdispenseSearchBySubject(
  client: SatuSehatClient, params: MedicationdispenseSearchBySubjectParams = {}
): Promise<FhirBundle<"MedicationDispense">> {
  return client.request("GET", "/MedicationDispense", {
    query: { subject: params.subject },
  }) as Promise<FhirBundle<"MedicationDispense">>;
}

export interface MedicationstatementRiwayatPengobatanObatDariFasyankesSendiriBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  dosage?: Array<Record<string, unknown>>;
  effectiveDateTime?: string;
  dateAsserted?: string;
  informationSource: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  contained?: Array<Record<string, unknown>>;
  medicationReference: {
    reference?: string;
    display?: string;
  };
}

/** MedicationStatement - Riwayat Pengobatan (Obat dari Fasyankes Sendiri) — POST /MedicationStatement */
export async function medicationstatementRiwayatPengobatanObatDariFasyankesSendiri(
  client: SatuSehatClient, body: MedicationstatementRiwayatPengobatanObatDariFasyankesSendiriBody
): Promise<unknown> {
  return client.request("POST", "/MedicationStatement", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}
