/**
 * rawat-jalan/cara-keluar-dari-rumah-sakit — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface EncounterUpdatePulangDanKontrolKembaliBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  serviceType: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
    end?: string;
  };
  length: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  location?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  hospitalization: {
    dischargeDisposition: {
      coding?: Array<Record<string, unknown>>;
      text?: string;
    };
  };
  serviceProvider: {
    reference?: string;
  };
}

/** Encounter - Update (Pulang dan Kontrol Kembali) — PUT /Encounter/:id */
export async function encounterUpdatePulangDanKontrolKembali(
  client: SatuSehatClient, id: string, body: EncounterUpdatePulangDanKontrolKembaliBody
): Promise<FhirResource> {
  return client.request("PUT", `/Encounter/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}
