/**
 * rawat-jalan/diagnosis — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ConditionPrimaryDengueBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  onsetDateTime?: string;
  recordedDate?: string;
  stage?: Array<Record<string, unknown>>;
}

/** Condition - Primary Dengue — POST /Condition */
export async function conditionPrimaryDengue(
  client: SatuSehatClient, body: ConditionPrimaryDengueBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

/** ClinicalImpression - PATCH Rasional Klinis — PATCH /ClinicalImpression/:id */
export async function clinicalimpressionPatchRasionalKlinis(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/ClinicalImpression/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
