/**
 * rawat-jalan/penilaian-risiko — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface RiskassessmentPenilaianRisikoBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  performer: {
    reference?: string;
  };
  condition: {
    reference?: string;
  };
  reasonReference?: Array<Record<string, unknown>>;
  prediction?: Array<Record<string, unknown>>;
  mitigation?: string;
}

/** RiskAssessment - Penilaian Risiko — POST /RiskAssessment */
export async function riskassessmentPenilaianRisiko(
  client: SatuSehatClient, body: RiskassessmentPenilaianRisikoBody
): Promise<unknown> {
  return client.request("POST", "/RiskAssessment", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

/** ClinicalImpression - PATCH Rasional Klinis — PATCH /ClinicalImpression/:id */
export async function clinicalimpressionPatchRasionalKlinis(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/ClinicalImpression/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}
