/**
 * rawat-jalan/prognosis — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ClinicalimpressionPrognosisBaikBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  date?: string;
  assessor: {
    reference?: string;
  };
  problem?: Array<Record<string, unknown>>;
  investigation?: Array<Record<string, unknown>>;
  summary?: string;
  finding?: Array<Record<string, unknown>>;
  prognosisCodeableConcept?: Array<Record<string, unknown>>;
}

/** ClinicalImpression - Prognosis Baik — POST /ClinicalImpression */
export async function clinicalimpressionPrognosisBaik(
  client: SatuSehatClient, body: ClinicalimpressionPrognosisBaikBody
): Promise<FhirResource<"ClinicalImpression">> {
  return client.request("POST", "/ClinicalImpression", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClinicalImpression">>;
}
