/**
 * rawat-jalan/rencana-rawat-pasien — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CareplanRencanaRawatPasienBody {
  resourceType?: string;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  title?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  created?: string;
  author: {
    reference?: string;
    display?: string;
  };
  goal?: Array<Record<string, unknown>>;
}

/** CarePlan - Rencana Rawat Pasien — POST /CarePlan */
export async function careplanRencanaRawatPasien(
  client: SatuSehatClient, body: CareplanRencanaRawatPasienBody
): Promise<FhirResource<"CarePlan">> {
  return client.request("POST", "/CarePlan", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CarePlan">>;
}
