/**
 * rawat-jalan/rencana-tindak-lanjut-dan-instruksi-tindak-lanjut — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ServicerequestKontrolKembaliBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  occurrenceDateTime?: string;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  locationReference?: Array<Record<string, unknown>>;
  patientInstruction?: string;
}

/** ServiceRequest - Kontrol kembali — POST /ServiceRequest */
export async function servicerequestKontrolKembali(
  client: SatuSehatClient, body: ServicerequestKontrolKembaliBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}
