/**
 * rawat-jalan/resume-medis — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CompositionResumeMedisBody {
  resourceType?: string;
  identifier: {
    system?: string;
    value?: string;
  };
  status?: string;
  category?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  date?: string;
  title?: string;
  author?: Array<Record<string, unknown>>;
  custodian: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  section?: Array<Record<string, unknown>>;
}

/** Composition - Resume Medis — POST /Composition */
export async function compositionResumeMedis(
  client: SatuSehatClient, body: CompositionResumeMedisBody
): Promise<FhirResource<"Composition">> {
  return client.request("POST", "/Composition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Composition">>;
}
