/**
 * rawat-jalan/riwayat-perjalanan-penyakit — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ClinicalimpressionRiwayatPerjalananPenyakitBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  date?: string;
  assessor: {
    reference?: string;
  };
  summary?: string;
}

/** ClinicalImpression - Riwayat Perjalanan Penyakit — POST /ClinicalImpression */
export async function clinicalimpressionRiwayatPerjalananPenyakit(
  client: SatuSehatClient, body: ClinicalimpressionRiwayatPerjalananPenyakitBody
): Promise<FhirResource<"ClinicalImpression">> {
  return client.request("POST", "/ClinicalImpression", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClinicalImpression">>;
}
