/**
 * rawat-jalan/tatalaksana — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface MedicationCreateBody {
  resourceType?: string;
  meta: {
    profile?: Array<string>;
  };
  identifier?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  status?: string;
  manufacturer: {
    reference?: string;
  };
  form: {
    coding?: Array<Record<string, unknown>>;
  };
  ingredient?: Array<Record<string, unknown>>;
  batch: {
    lotNumber?: string;
    expirationDate?: string;
  };
  extension?: Array<Record<string, unknown>>;
}

/** Medication - Create — POST /Medication */
export async function medicationCreate(
  client: SatuSehatClient, body: MedicationCreateBody
): Promise<FhirResource<"Medication">> {
  return client.request("POST", "/Medication", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Medication">>;
}

export interface MedicationrequestCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  priority?: string;
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  reasonReference?: Array<Record<string, unknown>>;
  dosageInstruction?: Array<Record<string, unknown>>;
  dispenseRequest: {
    dispenseInterval: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    validityPeriod: {
      start?: string;
      end?: string;
    };
    numberOfRepeatsAllowed?: number;
    quantity: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    expectedSupplyDuration: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    performer: {
      reference?: string;
    };
  };
  contained?: Array<Record<string, unknown>>;
  courseOfTherapyType: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** MedicationRequest - Create — POST /MedicationRequest */
export async function medicationrequestCreate(
  client: SatuSehatClient, body: MedicationrequestCreateBody
): Promise<FhirResource<"MedicationRequest">> {
  return client.request("POST", "/MedicationRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationRequest">>;
}

export interface QuestionnaireresponsePengkajianResepBody {
  resourceType?: string;
  questionnaire?: string;
  status?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authored?: string;
  author: {
    reference?: string;
    display?: string;
  };
  source: {
    reference?: string;
  };
  item?: Array<Record<string, unknown>>;
}

/** QuestionnaireResponse - Pengkajian Resep — POST /QuestionnaireResponse */
export async function questionnaireresponsePengkajianResep(
  client: SatuSehatClient, body: QuestionnaireresponsePengkajianResepBody
): Promise<FhirResource<"QuestionnaireResponse">> {
  return client.request("POST", "/QuestionnaireResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"QuestionnaireResponse">>;
}

export interface MedicationdispenseCreateBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  authorizingPrescription?: Array<Record<string, unknown>>;
  quantity: {
    system?: string;
    code?: string;
    value?: number;
  };
  daysSupply: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  whenPrepared?: string;
  whenHandedOver?: string;
  dosageInstruction?: Array<Record<string, unknown>>;
  contained?: Array<Record<string, unknown>>;
}

/** MedicationDispense - Create — POST /MedicationDispense */
export async function medicationdispenseCreate(
  client: SatuSehatClient, body: MedicationdispenseCreateBody
): Promise<FhirResource<"MedicationDispense">> {
  return client.request("POST", "/MedicationDispense", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationDispense">>;
}

export interface MedicationadministrationCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  effectivePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  request: {
    reference?: string;
  };
  dosage: {
    site: {
      coding?: Array<Record<string, unknown>>;
    };
    route: {
      coding?: Array<Record<string, unknown>>;
    };
    dose: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
  };
}

/** MedicationAdministration - Create — POST /MedicationAdministration */
export async function medicationadministrationCreate(
  client: SatuSehatClient, body: MedicationadministrationCreateBody
): Promise<unknown> {
  return client.request("POST", "/MedicationAdministration", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface NutritionorderDietBody {
  resourceType?: string;
  status?: string;
  intent?: string;
  patient: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  dateTime?: string;
  orderer: {
    reference?: string;
  };
  excludeFoodModifier?: Array<Record<string, unknown>>;
  oralDiet: {
    type?: Array<Record<string, unknown>>;
    nutrient?: Array<Record<string, unknown>>;
  };
}

/** NutritionOrder - Diet — POST /NutritionOrder */
export async function nutritionorderDiet(
  client: SatuSehatClient, body: NutritionorderDietBody
): Promise<unknown> {
  return client.request("POST", "/NutritionOrder", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface ProcedureEdukasiBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
}

/** Procedure - Edukasi — POST /Procedure */
export async function procedureEdukasi(
  client: SatuSehatClient, body: ProcedureEdukasiBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}
