/**
 * rawat-jalan/tindakan-prosedur-medis — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ServicerequestEkgBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  occurrenceDateTime?: string;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** ServiceRequest - EKG — POST /ServiceRequest */
export async function servicerequestEkg(
  client: SatuSehatClient, body: ServicerequestEkgBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}

export interface ProcedureEkgBody {
  resourceType?: string;
  basedOn?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    end?: string;
    start?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
  usedCode?: Array<Record<string, unknown>>;
}

/** Procedure - EKG — POST /Procedure */
export async function procedureEkg(
  client: SatuSehatClient, body: ProcedureEkgBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}

export interface ObservationEkgBody {
  resourceType?: string;
  status?: string;
  basedOn?: Array<Record<string, unknown>>;
  partOf?: Array<Record<string, unknown>>;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  component?: Array<Record<string, unknown>>;
  valueString?: string;
}

/** Observation - EKG — POST /Observation */
export async function observationEkg(
  client: SatuSehatClient, body: ObservationEkgBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}
