/**
 * rawat-jalan/tujuan-perawatan — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";

export interface GoalCreateTujuanPerawatanBody {
  resourceType?: string;
  lifecycleStatus?: string;
  category?: Array<Record<string, unknown>>;
  description: {
    text?: string;
  };
  subject: {
    reference?: string;
  };
  target?: Array<Record<string, unknown>>;
  statusDate?: string;
  expressedBy: {
    reference?: string;
  };
  addresses?: Array<Record<string, unknown>>;
}

/** Goal - Create - Tujuan Perawatan — POST /Goal */
export async function goalCreateTujuanPerawatan(
  client: SatuSehatClient, body: GoalCreateTujuanPerawatanBody
): Promise<unknown> {
  return client.request("POST", "/Goal", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface GoalUpdateTujuanPerawatanBody {
  resourceType?: string;
  id?: string;
  lifecycleStatus?: string;
  achievementStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  description: {
    text?: string;
  };
  subject: {
    reference?: string;
  };
  target?: Array<Record<string, unknown>>;
  statusDate?: string;
  expressedBy: {
    reference?: string;
  };
  addresses?: Array<Record<string, unknown>>;
  outcomeCode?: Array<Record<string, unknown>>;
}

/** Goal - Update - Tujuan Perawatan — PUT /Goal/:id */
export async function goalUpdateTujuanPerawatan(
  client: SatuSehatClient, id: string, body: GoalUpdateTujuanPerawatanBody
): Promise<unknown> {
  return client.request("PUT", `/Goal/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}
