/**
 * rawat-jalan/variasi-rtl-dan-cara-keluar — generated by scripts/generate-modules.mjs
 * from "01. Pelayanan - Rawat Jalan.postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface ServicerequestRujukanKeRawatInapDiFaskesLainDenganAmbulansBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  occurrenceDateTime?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  locationCode?: Array<Record<string, unknown>>;
  patientInstruction?: string;
}

/** ServiceRequest - Rujukan ke Rawat Inap di Faskes Lain dengan Ambulans — POST /ServiceRequest */
export async function servicerequestRujukanKeRawatInapDiFaskesLainDenganAmbulans(
  client: SatuSehatClient, body: ServicerequestRujukanKeRawatInapDiFaskesLainDenganAmbulansBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}

export interface EncounterUpdateRujukanEksternalBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
    end?: string;
  };
  location?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  hospitalization: {
    dischargeDisposition: {
      coding?: Array<Record<string, unknown>>;
      text?: string;
    };
  };
  serviceProvider: {
    reference?: string;
  };
}

/** Encounter - Update (Rujukan Eksternal) — PUT /Encounter/:id */
export async function encounterUpdateRujukanEksternal(
  client: SatuSehatClient, id: string, body: EncounterUpdateRujukanEksternalBody
): Promise<FhirResource> {
  return client.request("PUT", `/Encounter/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}
