/**
 * klaim-swasta/komunikasi — generated by scripts/generate-modules.mjs
 * from "25. Use Case - Modul Klaim (Asuransi Swasta).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";

export interface CommunicationrequestBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  payload?: Array<Record<string, unknown>>;
  about?: Array<Record<string, unknown>>;
  sender: {
    reference?: string;
  };
  recipient?: Array<Record<string, unknown>>;
}

/** CommunicationRequest — POST /CommunicationRequest */
export async function communicationrequest(
  client: SatuSehatClient, body: CommunicationrequestBody
): Promise<unknown> {
  return client.request("POST", "/CommunicationRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface CommunicationKe1Body {
  resourceType?: string;
  status?: string;
  basedOn?: Array<Record<string, unknown>>;
  payload?: Array<Record<string, unknown>>;
  about?: Array<Record<string, unknown>>;
  inResponseTo?: Array<Record<string, unknown>>;
  sender: {
    reference?: string;
  };
  recipient?: Array<Record<string, unknown>>;
}

/** Communication ke-1 — POST /Communication */
export async function communicationKe1(
  client: SatuSehatClient, body: CommunicationKe1Body
): Promise<unknown> {
  return client.request("POST", "/Communication", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}
