/**
 * klaim-swasta/oop — generated by scripts/generate-modules.mjs
 * from "25. Use Case - Modul Klaim (Asuransi Swasta).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface AccountAkunPasienBody {
  resourceType?: string;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  name?: string;
  subject?: Array<Record<string, unknown>>;
  servicePeriod: {
    start?: string;
    end?: string;
  };
  owner: {
    reference?: string;
  };
  guarantor?: Array<Record<string, unknown>>;
  description?: string;
}

/** Account - Akun Pasien — POST /Account */
export async function accountAkunPasien(
  client: SatuSehatClient, body: AccountAkunPasienBody
): Promise<FhirResource<"Account">> {
  return client.request("POST", "/Account", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Account">>;
}

/** Encounter - Account — PATCH /Encounter/:id */
export async function encounterAccount(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Encounter/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface ChargeitemParatiroidektomiParsialBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  occurrencePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  quantity: {
    value?: number;
  };
  account?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** ChargeItem - Paratiroidektomi Parsial — POST /ChargeItem */
export async function chargeitemParatiroidektomiParsial(
  client: SatuSehatClient, body: ChargeitemParatiroidektomiParsialBody
): Promise<FhirResource<"ChargeItem">> {
  return client.request("POST", "/ChargeItem", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ChargeItem">>;
}

export interface InvoiceInvoiceBody {
  resourceType?: string;
  status?: string;
  subject: {
    reference?: string;
  };
  date?: string;
  issuer: {
    reference?: string;
  };
  account: {
    reference?: string;
  };
  lineItem?: Array<Record<string, unknown>>;
  totalNet: {
    value?: number;
    currency?: string;
  };
}

/** Invoice - Invoice — POST /Invoice */
export async function invoiceInvoice(
  client: SatuSehatClient, body: InvoiceInvoiceBody
): Promise<FhirResource<"Invoice">> {
  return client.request("POST", "/Invoice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Invoice">>;
}

export interface PaymentreconcilliationRekonsiliasiPembayaranBody {
  resourceType?: string;
  status?: string;
  period: {
    start?: string;
    end?: string;
  };
  created?: string;
  paymentIssuer: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  paymentDate?: string;
  paymentAmount: {
    value?: number;
    currency?: string;
  };
  detail?: Array<Record<string, unknown>>;
  processNote?: Array<Record<string, unknown>>;
}

/** PaymentReconcilliation - Rekonsiliasi Pembayaran — POST /PaymentReconciliation */
export async function paymentreconcilliationRekonsiliasiPembayaran(
  client: SatuSehatClient, body: PaymentreconcilliationRekonsiliasiPembayaranBody
): Promise<FhirResource<"PaymentReconciliation">> {
  return client.request("POST", "/PaymentReconciliation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentReconciliation">>;
}

export interface PaymentnoticeNotifikasiPembayaranBody {
  resourceType?: string;
  status?: string;
  request: {
    reference?: string;
  };
  created?: string;
  paymentDate?: string;
  provider: {
    reference?: string;
  };
  payee: {
    reference?: string;
  };
  recipient: {
    reference?: string;
  };
  amount: {
    value?: number;
    currency?: string;
  };
  payment: {
    reference?: string;
  };
  paymentStatus: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** PaymentNotice - Notifikasi Pembayaran — POST /PaymentNotice */
export async function paymentnoticeNotifikasiPembayaran(
  client: SatuSehatClient, body: PaymentnoticeNotifikasiPembayaranBody
): Promise<FhirResource<"PaymentNotice">> {
  return client.request("POST", "/PaymentNotice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentNotice">>;
}
