/**
 * klaim-swasta/primary-payor — generated by scripts/generate-modules.mjs
 * from "25. Use Case - Modul Klaim (Asuransi Swasta).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

// Search/create/lookup already implemented once in src/common/*.ts.
export { createOrganization, createLocation } from "../common/organization.js";
export { searchPatient, getPatientById, getPractitionerById } from "../common/search.js";

export interface CoverageKepesertaanAsuransiSwastaKe1Body {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  policyHolder: {
    reference?: string;
  };
  subscriber: {
    reference?: string;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - Asuransi Swasta ke-1 — POST /Coverage */
export async function coverageKepesertaanAsuransiSwastaKe1(
  client: SatuSehatClient, body: CoverageKepesertaanAsuransiSwastaKe1Body
): Promise<FhirResource<"Coverage">> {
  return client.request("POST", "/Coverage", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Coverage">>;
}

export interface CoverageKepesertaanAsuransiSwastaKe1UpdateBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  policyHolder: {
    reference?: string;
  };
  subscriber: {
    reference?: string;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - Asuransi Swasta ke-1 - Update — PUT /Coverage/:id */
export async function coverageKepesertaanAsuransiSwastaKe1Update(
  client: SatuSehatClient, id: string, body: CoverageKepesertaanAsuransiSwastaKe1UpdateBody
): Promise<FhirResource> {
  return client.request("PUT", `/Coverage/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

export interface CoverageMendapatkanDataKepesertaanParams {
    patient?: string | number;
    identifier?: string | number;
}

/** Coverage - Mendapatkan Data Kepesertaan — GET /Coverage */
export async function coverageMendapatkanDataKepesertaan(
  client: SatuSehatClient, params: CoverageMendapatkanDataKepesertaanParams = {}
): Promise<FhirBundle<"Coverage">> {
  return client.request("GET", "/Coverage", {
    query: { patient: params.patient, identifier: params.identifier },
  }) as Promise<FhirBundle<"Coverage">>;
}

/** Location - Create Bed 104 Kelas VIP - Occupied — PATCH /Location/:id */
export async function locationCreateBed104KelasVipOccupied(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Location/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface EpisodeofcareByIdParams {
    patient?: string | number;
    type?: string | number;
    status?: string | number;
}

/** EpisodeOfCare - By ID — GET /EpisodeOfCare */
export async function episodeofcareById(
  client: SatuSehatClient, params: EpisodeofcareByIdParams = {}
): Promise<FhirBundle<"EpisodeOfCare">> {
  return client.request("GET", "/EpisodeOfCare", {
    query: { patient: params.patient, type: params.type, status: params.status },
  }) as Promise<FhirBundle<"EpisodeOfCare">>;
}

export interface EncounterKunjunganBaruRawatInapBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  location?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  serviceProvider: {
    reference?: string;
  };
  basedOn?: Array<Record<string, unknown>>;
  episodeOfCare?: Array<Record<string, unknown>>;
}

/** Encounter - Kunjungan Baru Rawat Inap — POST /Encounter */
export async function encounterKunjunganBaruRawatInap(
  client: SatuSehatClient, body: EncounterKunjunganBaruRawatInapBody
): Promise<FhirResource<"Encounter">> {
  return client.request("POST", "/Encounter", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Encounter">>;
}

export interface EncounterMasukHcuBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  class: {
    system?: string;
    code?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  participant?: Array<Record<string, unknown>>;
  period: {
    start?: string;
  };
  length: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  location?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  statusHistory?: Array<Record<string, unknown>>;
  hospitalization: {
    dischargeDisposition: {
      coding?: Array<Record<string, unknown>>;
      text?: string;
    };
  };
  serviceProvider: {
    reference?: string;
  };
  basedOn?: Array<Record<string, unknown>>;
  episodeOfCare?: Array<Record<string, unknown>>;
}

/** Encounter - Masuk HCU — PUT /Encounter/:id */
export async function encounterMasukHcu(
  client: SatuSehatClient, id: string, body: EncounterMasukHcuBody
): Promise<FhirResource> {
  return client.request("PUT", `/Encounter/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource>;
}

export interface AccountAkunPasienBody {
  resourceType?: string;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  name?: string;
  subject?: Array<Record<string, unknown>>;
  servicePeriod: {
    start?: string;
    end?: string;
  };
  coverage?: Array<Record<string, unknown>>;
  owner: {
    reference?: string;
  };
  description?: string;
}

/** Account - Akun Pasien — POST /Account */
export async function accountAkunPasien(
  client: SatuSehatClient, body: AccountAkunPasienBody
): Promise<FhirResource<"Account">> {
  return client.request("POST", "/Account", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Account">>;
}

/** Encounter - Account — PATCH /Encounter/:id */
export async function encounterAccount(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Encounter/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface ConditionKeluhanUtamaBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  stage?: Array<Record<string, unknown>>;
  recordedDate?: string;
  onsetDateTime?: string;
  note?: Array<Record<string, unknown>>;
  onsetPeriod: {
    start?: string;
    end?: string;
  };
  recorder: {
    reference?: string;
  };
}

/** Condition - Keluhan Utama — POST /Condition */
export async function conditionKeluhanUtama(
  client: SatuSehatClient, body: ConditionKeluhanUtamaBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

export interface FamilymemberhistoryRiwayatPenyakitKeluargaBody {
  resourceType?: string;
  status?: string;
  relationship: {
    coding?: Array<Record<string, unknown>>;
  };
  deceasedBoolean?: boolean;
  patient: {
    reference?: string;
    display?: string;
  };
  date?: string;
  condition?: Array<Record<string, unknown>>;
}

/** FamilyMemberHistory - Riwayat Penyakit Keluarga — POST /FamilyMemberHistory */
export async function familymemberhistoryRiwayatPenyakitKeluarga(
  client: SatuSehatClient, body: FamilymemberhistoryRiwayatPenyakitKeluargaBody
): Promise<unknown> {
  return client.request("POST", "/FamilyMemberHistory", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface AllergyintoleranceAlergiAspirinBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<string>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  patient: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  recordedDate?: string;
  recorder: {
    reference?: string;
  };
}

/** AllergyIntolerance - Alergi Aspirin — POST /AllergyIntolerance */
export async function allergyintoleranceAlergiAspirin(
  client: SatuSehatClient, body: AllergyintoleranceAlergiAspirinBody
): Promise<FhirResource<"AllergyIntolerance">> {
  return client.request("POST", "/AllergyIntolerance", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"AllergyIntolerance">>;
}

export interface MedicationdispenseSearchBySubjectParams {
    subject?: string | number;
}

/** MedicationDispense - Search by Subject — GET /MedicationDispense */
export async function medicationdispenseSearchBySubject(
  client: SatuSehatClient, params: MedicationdispenseSearchBySubjectParams = {}
): Promise<FhirBundle<"MedicationDispense">> {
  return client.request("GET", "/MedicationDispense", {
    query: { subject: params.subject },
  }) as Promise<FhirBundle<"MedicationDispense">>;
}

export interface MedicationstatementRiwayatPengobatanBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  dosage?: Array<Record<string, unknown>>;
  effectiveDateTime?: string;
  dateAsserted?: string;
  informationSource: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
}

/** MedicationStatement - Riwayat Pengobatan — POST /MedicationStatement */
export async function medicationstatementRiwayatPengobatan(
  client: SatuSehatClient, body: MedicationstatementRiwayatPengobatanBody
): Promise<unknown> {
  return client.request("POST", "/MedicationStatement", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface ObservationSadarPenuhBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  encounter: {
    reference?: string;
    display?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  valueCodeableConcept: {
    coding?: Array<Record<string, unknown>>;
  };
  identifier?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  bodySite: {
    coding?: Array<Record<string, unknown>>;
  };
  derivedFrom?: Array<Record<string, unknown>>;
  valueString?: string;
  specimen: {
    reference?: string;
  };
  valueQuantity: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  interpretation?: Array<Record<string, unknown>>;
  referenceRange?: Array<Record<string, unknown>>;
}

/** Observation - Sadar Penuh — POST /Observation */
export async function observationSadarPenuh(
  client: SatuSehatClient, body: ObservationSadarPenuhBody
): Promise<FhirResource<"Observation">> {
  return client.request("POST", "/Observation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Observation">>;
}

export interface ClinicalimpressionRiwayatPerjalananPenyakitBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  date?: string;
  assessor: {
    reference?: string;
  };
  problem?: Array<Record<string, unknown>>;
  investigation?: Array<Record<string, unknown>>;
  summary?: string;
  finding?: Array<Record<string, unknown>>;
  prognosisCodeableConcept?: Array<Record<string, unknown>>;
}

/** ClinicalImpression - Riwayat Perjalanan Penyakit — POST /ClinicalImpression */
export async function clinicalimpressionRiwayatPerjalananPenyakit(
  client: SatuSehatClient, body: ClinicalimpressionRiwayatPerjalananPenyakitBody
): Promise<FhirResource<"ClinicalImpression">> {
  return client.request("POST", "/ClinicalImpression", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClinicalImpression">>;
}

export interface GoalCreateTujuanPerawatanBody {
  resourceType?: string;
  lifecycleStatus?: string;
  category?: Array<Record<string, unknown>>;
  description: {
    text?: string;
  };
  subject: {
    reference?: string;
  };
  target?: Array<Record<string, unknown>>;
  statusDate?: string;
  expressedBy: {
    reference?: string;
  };
  addresses?: Array<Record<string, unknown>>;
}

/** Goal - Create - Tujuan Perawatan — POST /Goal */
export async function goalCreateTujuanPerawatan(
  client: SatuSehatClient, body: GoalCreateTujuanPerawatanBody
): Promise<unknown> {
  return client.request("POST", "/Goal", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface GoalUpdateTujuanPerawatanBody {
  resourceType?: string;
  id?: string;
  lifecycleStatus?: string;
  achievementStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  description: {
    text?: string;
  };
  subject: {
    reference?: string;
  };
  target?: Array<Record<string, unknown>>;
  statusDate?: string;
  expressedBy: {
    reference?: string;
  };
  addresses?: Array<Record<string, unknown>>;
  outcomeCode?: Array<Record<string, unknown>>;
}

/** Goal - Update - Tujuan Perawatan — PUT /Goal/:id */
export async function goalUpdateTujuanPerawatan(
  client: SatuSehatClient, id: string, body: GoalUpdateTujuanPerawatanBody
): Promise<unknown> {
  return client.request("PUT", `/Goal/${id}`, {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface CareplanRencanaRawatPasienBody {
  resourceType?: string;
  title?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  intent?: string;
  description?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  created?: string;
  author: {
    reference?: string;
  };
  goal?: Array<Record<string, unknown>>;
}

/** CarePlan - Rencana Rawat Pasien — POST /CarePlan */
export async function careplanRencanaRawatPasien(
  client: SatuSehatClient, body: CareplanRencanaRawatPasienBody
): Promise<FhirResource<"CarePlan">> {
  return client.request("POST", "/CarePlan", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CarePlan">>;
}

export interface ProcedureStatusPuasaBody {
  resourceType?: string;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  performedPeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** Procedure - Status Puasa — POST /Procedure */
export async function procedureStatusPuasa(
  client: SatuSehatClient, body: ProcedureStatusPuasaBody
): Promise<FhirResource<"Procedure">> {
  return client.request("POST", "/Procedure", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Procedure">>;
}

export interface ServicerequestHematologiRutinBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  priority?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
    text?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
    display?: string;
  };
  occurrenceDateTime?: string;
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  locationCode?: Array<Record<string, unknown>>;
  patientInstruction?: string;
  reasonReference?: Array<Record<string, unknown>>;
  orderDetail?: Array<Record<string, unknown>>;
  bodySite?: Array<Record<string, unknown>>;
  supportingInfo?: Array<Record<string, unknown>>;
  note?: Array<Record<string, unknown>>;
}

/** ServiceRequest - Hematologi Rutin — POST /ServiceRequest */
export async function servicerequestHematologiRutin(
  client: SatuSehatClient, body: ServicerequestHematologiRutinBody
): Promise<FhirResource<"ServiceRequest">> {
  return client.request("POST", "/ServiceRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ServiceRequest">>;
}

export interface SpecimenBloodBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  condition?: Array<Record<string, unknown>>;
  collection: {
    method: {
      coding?: Array<Record<string, unknown>>;
    };
    collectedDateTime?: string;
    quantity: {
      value?: number;
      unit?: string;
    };
    collector: {
      reference?: string;
      display?: string;
    };
    fastingStatusCodeableConcept: {
      coding?: Array<Record<string, unknown>>;
    };
  };
  subject: {
    reference?: string;
    display?: string;
  };
  request?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
  receivedTime?: string;
  processing?: Array<Record<string, unknown>>;
}

/** Specimen - Blood — POST /Specimen */
export async function specimenBlood(
  client: SatuSehatClient, body: SpecimenBloodBody
): Promise<FhirResource<"Specimen">> {
  return client.request("POST", "/Specimen", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Specimen">>;
}

export interface DiagnosticreportHematologiRutinBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  effectiveDateTime?: string;
  issued?: string;
  performer?: Array<Record<string, unknown>>;
  imagingStudy?: Array<Record<string, unknown>>;
  result?: Array<Record<string, unknown>>;
  basedOn?: Array<Record<string, unknown>>;
  conclusion?: string;
  specimen?: Array<Record<string, unknown>>;
  conclusionCode?: Array<Record<string, unknown>>;
}

/** DiagnosticReport - Hematologi Rutin — POST /DiagnosticReport */
export async function diagnosticreportHematologiRutin(
  client: SatuSehatClient, body: DiagnosticreportHematologiRutinBody
): Promise<FhirResource<"DiagnosticReport">> {
  return client.request("POST", "/DiagnosticReport", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"DiagnosticReport">>;
}

export interface ImagingstudyGetIdBasedOnAccessionNumberParams {
    identifier?: string | number;
}

/** ImagingStudy - Get ID based on Accession Number — GET /ImagingStudy */
export async function imagingstudyGetIdBasedOnAccessionNumber(
  client: SatuSehatClient, params: ImagingstudyGetIdBasedOnAccessionNumberParams = {}
): Promise<FhirBundle<"ImagingStudy">> {
  return client.request("GET", "/ImagingStudy", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"ImagingStudy">>;
}

export interface CoverageeligibilityrequestRequestSepKeAsuransiSwastaBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  priority: {
    coding?: Array<Record<string, unknown>>;
  };
  purpose?: Array<string>;
  patient: {
    reference?: string;
  };
  servicedDate?: string;
  created?: string;
  enterer: {
    reference?: string;
  };
  provider: {
    reference?: string;
  };
  insurer: {
    reference?: string;
  };
  facility: {
    reference?: string;
  };
  insurance?: Array<Record<string, unknown>>;
  supportingInfo?: Array<Record<string, unknown>>;
  contained?: Array<Record<string, unknown>>;
}

/** CoverageEligibilityRequest - Request SEP ke Asuransi Swasta — POST /CoverageEligibilityRequest */
export async function coverageeligibilityrequestRequestSepKeAsuransiSwasta(
  client: SatuSehatClient, body: CoverageeligibilityrequestRequestSepKeAsuransiSwastaBody
): Promise<FhirResource<"CoverageEligibilityRequest">> {
  return client.request("POST", "/CoverageEligibilityRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CoverageEligibilityRequest">>;
}

export interface CoverageeligibilityrequestGetByIdentifierParams {
    identifier?: string | number;
    patient?: string | number;
}

/** CoverageEligibilityRequest - GET By Identifier — GET /CoverageEligibilityRequest */
export async function coverageeligibilityrequestGetByIdentifier(
  client: SatuSehatClient, params: CoverageeligibilityrequestGetByIdentifierParams = {}
): Promise<FhirBundle<"CoverageEligibilityRequest">> {
  return client.request("GET", "/CoverageEligibilityRequest", {
    query: { identifier: params.identifier, patient: params.patient },
  }) as Promise<FhirBundle<"CoverageEligibilityRequest">>;
}

/** CoverageEligibilityRequest - GET Everything — GET /CoverageEligibilityRequest/{{CoverageEligibilityRequest_id}}/$everything */
export async function coverageeligibilityrequestGetEverything(
  client: SatuSehatClient, coverageeligibilityrequestId: string
): Promise<FhirBundle<"CoverageEligibilityRequest">> {
  return client.request("GET", `/CoverageEligibilityRequest/${coverageeligibilityrequestId}/$everything`) as Promise<FhirBundle<"CoverageEligibilityRequest">>;
}

export interface CoverageeligibilityresponseResponseSepBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  purpose?: Array<string>;
  patient: {
    reference?: string;
  };
  created?: string;
  requestor: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  insurer: {
    reference?: string;
  };
  insurance?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** CoverageEligibilityResponse - Response SEP — POST /CoverageEligibilityResponse */
export async function coverageeligibilityresponseResponseSep(
  client: SatuSehatClient, body: CoverageeligibilityresponseResponseSepBody
): Promise<FhirResource<"CoverageEligibilityResponse">> {
  return client.request("POST", "/CoverageEligibilityResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CoverageEligibilityResponse">>;
}

export interface CoverageeligibilityresponseGetByIdRequestParams {
    request?: string | number;
}

/** CoverageEligibilityResponse - GET by ID Request — GET /CoverageEligibilityResponse/ */
export async function coverageeligibilityresponseGetByIdRequest(
  client: SatuSehatClient, params: CoverageeligibilityresponseGetByIdRequestParams = {}
): Promise<FhirBundle<"CoverageEligibilityResponse">> {
  return client.request("GET", "/CoverageEligibilityResponse/", {
    query: { request: params.request },
  }) as Promise<FhirBundle<"CoverageEligibilityResponse">>;
}

export interface ChargeitemParatiroidektomiParsialBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  chargeItem: {
    reference?: string;
  };
  coverage: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  quantity: {
    value?: number;
  };
  total: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  excess: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  context: {
    reference?: string;
  };
  occurrencePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  account?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** ChargeItem - Paratiroidektomi Parsial — POST /ChargeItem */
export async function chargeitemParatiroidektomiParsial(
  client: SatuSehatClient, body: ChargeitemParatiroidektomiParsialBody
): Promise<FhirResource<"ChargeItem">> {
  return client.request("POST", "/ChargeItem", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ChargeItem">>;
}

/** Encounter - GET untuk membaca Account — GET /Encounter/:id */
export async function encounterGetUntukMembacaAccount(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"Encounter">> {
  return client.request("GET", `/Encounter/${id}`) as Promise<FhirResource<"Encounter">>;
}

export interface ChargeitemGetByAccountIdAndPatientIdParams {
    account?: string | number;
    subject?: string | number;
    id?: string | number;
}

/** ChargeItem - GET by Account_id and Patient_id — GET /ChargeItem */
export async function chargeitemGetByAccountIdAndPatientId(
  client: SatuSehatClient, params: ChargeitemGetByAccountIdAndPatientIdParams = {}
): Promise<FhirBundle<"ChargeItem">> {
  return client.request("GET", "/ChargeItem", {
    query: { account: params.account, subject: params.subject, _id: params.id },
  }) as Promise<FhirBundle<"ChargeItem">>;
}

/** ChargeItem - GET By ID — GET /ChargeItem/:id */
export async function chargeitemGetById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"ChargeItem">> {
  return client.request("GET", `/ChargeItem/${id}`) as Promise<FhirResource<"ChargeItem">>;
}

export interface ChargeitemresponseDenganPriceoverrideBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status: {
    coding?: Array<Record<string, unknown>>;
  };
  chargeItem: {
    reference?: string;
  };
  coverage: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  payor: {
    reference?: string;
  };
  quantity: {
    value?: number;
  };
  total: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  excess: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  unitPriceOverride: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  factorOverride?: number;
  overrideReason: {
    text?: string;
  };
}

/** ChargeItemResponse - dengan priceOverride — POST /ChargeItemResponse */
export async function chargeitemresponseDenganPriceoverride(
  client: SatuSehatClient, body: ChargeitemresponseDenganPriceoverrideBody
): Promise<unknown> {
  return client.request("POST", "/ChargeItemResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface ConditionPerluasanLateralitasMetastasisBody {
  resourceType?: string;
  clinicalStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  verificationStatus: {
    coding?: Array<Record<string, unknown>>;
  };
  category?: Array<Record<string, unknown>>;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  bodySite?: Array<Record<string, unknown>>;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  recordedDate?: string;
}

/** Condition - Perluasan, Lateralitas, Metastasis — POST /Condition/ */
export async function conditionPerluasanLateralitasMetastasis(
  client: SatuSehatClient, body: ConditionPerluasanLateralitasMetastasisBody
): Promise<FhirResource<"Condition">> {
  return client.request("POST", "/Condition/", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Condition">>;
}

export interface RiskassessmentPenilaianRisikoBody {
  resourceType?: string;
  status?: string;
  code: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  performer: {
    reference?: string;
  };
  condition: {
    reference?: string;
  };
  reasonReference?: Array<Record<string, unknown>>;
  prediction?: Array<Record<string, unknown>>;
  mitigation?: string;
}

/** RiskAssessment - Penilaian Risiko — POST /RiskAssessment */
export async function riskassessmentPenilaianRisiko(
  client: SatuSehatClient, body: RiskassessmentPenilaianRisikoBody
): Promise<unknown> {
  return client.request("POST", "/RiskAssessment", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

/** ClinicalImpression - PATCH Rasional Klinis — PATCH /ClinicalImpression/:id */
export async function clinicalimpressionPatchRasionalKlinis(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/ClinicalImpression/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface MedicationrequestCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  intent?: string;
  category?: Array<Record<string, unknown>>;
  priority?: string;
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authoredOn?: string;
  requester: {
    reference?: string;
    display?: string;
  };
  dosageInstruction?: Array<Record<string, unknown>>;
  dispenseRequest: {
    dispenseInterval: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
    validityPeriod: {
      start?: string;
      end?: string;
    };
    numberOfRepeatsAllowed?: number;
    quantity: {
      value?: number;
      unit?: string;
      code?: string;
      system?: string;
    };
    expectedSupplyDuration: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
  };
}

/** MedicationRequest - Create — POST /MedicationRequest */
export async function medicationrequestCreate(
  client: SatuSehatClient, body: MedicationrequestCreateBody
): Promise<FhirResource<"MedicationRequest">> {
  return client.request("POST", "/MedicationRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationRequest">>;
}

export interface QuestionnaireresponsePengkajianResepBody {
  resourceType?: string;
  questionnaire?: string;
  status?: string;
  subject: {
    reference?: string;
    display?: string;
  };
  encounter: {
    reference?: string;
  };
  authored?: string;
  author: {
    reference?: string;
    display?: string;
  };
  source: {
    reference?: string;
  };
  item?: Array<Record<string, unknown>>;
}

/** QuestionnaireResponse - Pengkajian Resep — POST /QuestionnaireResponse */
export async function questionnaireresponsePengkajianResep(
  client: SatuSehatClient, body: QuestionnaireresponsePengkajianResepBody
): Promise<FhirResource<"QuestionnaireResponse">> {
  return client.request("POST", "/QuestionnaireResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"QuestionnaireResponse">>;
}

export interface MedicationdispenseCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
    display?: string;
  };
  subject: {
    reference?: string;
    display?: string;
  };
  context: {
    reference?: string;
  };
  performer?: Array<Record<string, unknown>>;
  location: {
    reference?: string;
    display?: string;
  };
  authorizingPrescription?: Array<Record<string, unknown>>;
  quantity: {
    system?: string;
    code?: string;
    value?: number;
  };
  daysSupply: {
    value?: number;
    unit?: string;
    system?: string;
    code?: string;
  };
  whenPrepared?: string;
  whenHandedOver?: string;
  dosageInstruction?: Array<Record<string, unknown>>;
}

/** MedicationDispense - Create — POST /MedicationDispense */
export async function medicationdispenseCreate(
  client: SatuSehatClient, body: MedicationdispenseCreateBody
): Promise<FhirResource<"MedicationDispense">> {
  return client.request("POST", "/MedicationDispense", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"MedicationDispense">>;
}

export interface MedicationadministrationCreateBody {
  resourceType?: string;
  contained?: Array<Record<string, unknown>>;
  status?: string;
  category: {
    coding?: Array<Record<string, unknown>>;
  };
  medicationReference: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  context: {
    reference?: string;
  };
  effectivePeriod: {
    start?: string;
    end?: string;
  };
  performer?: Array<Record<string, unknown>>;
  reasonCode?: Array<Record<string, unknown>>;
  request: {
    reference?: string;
  };
  dosage: {
    site: {
      coding?: Array<Record<string, unknown>>;
    };
    route: {
      coding?: Array<Record<string, unknown>>;
    };
    dose: {
      value?: number;
      unit?: string;
      system?: string;
      code?: string;
    };
  };
}

/** MedicationAdministration - Create — POST /MedicationAdministration */
export async function medicationadministrationCreate(
  client: SatuSehatClient, body: MedicationadministrationCreateBody
): Promise<unknown> {
  return client.request("POST", "/MedicationAdministration", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface NutritionorderDietBody {
  resourceType?: string;
  status?: string;
  intent?: string;
  patient: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  dateTime?: string;
  orderer: {
    reference?: string;
  };
  excludeFoodModifier?: Array<Record<string, unknown>>;
  oralDiet: {
    type?: Array<Record<string, unknown>>;
    nutrient?: Array<Record<string, unknown>>;
  };
}

/** NutritionOrder - Diet — POST /NutritionOrder */
export async function nutritionorderDiet(
  client: SatuSehatClient, body: NutritionorderDietBody
): Promise<unknown> {
  return client.request("POST", "/NutritionOrder", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface CompositionResumeMedisBody {
  resourceType?: string;
  status?: string;
  category?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  subject: {
    reference?: string;
  };
  date?: string;
  title?: string;
  author?: Array<Record<string, unknown>>;
  custodian: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  section?: Array<Record<string, unknown>>;
}

/** Composition - Resume Medis — POST /Composition */
export async function compositionResumeMedis(
  client: SatuSehatClient, body: CompositionResumeMedisBody
): Promise<FhirResource<"Composition">> {
  return client.request("POST", "/Composition", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Composition">>;
}

export interface InvoiceInvoiceBody {
  resourceType?: string;
  status?: string;
  subject: {
    reference?: string;
  };
  date?: string;
  issuer: {
    reference?: string;
  };
  account: {
    reference?: string;
  };
  lineItem?: Array<Record<string, unknown>>;
  totalNet: {
    value?: number;
    currency?: string;
  };
}

/** Invoice - Invoice — POST /Invoice */
export async function invoiceInvoice(
  client: SatuSehatClient, body: InvoiceInvoiceBody
): Promise<FhirResource<"Invoice">> {
  return client.request("POST", "/Invoice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Invoice">>;
}

export interface ClaimDataKlaimAsuransiSwastaBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  use?: string;
  patient: {
    reference?: string;
  };
  billablePeriod: {
    start?: string;
    end?: string;
  };
  created?: string;
  enterer: {
    reference?: string;
  };
  insurer: {
    reference?: string;
  };
  provider: {
    reference?: string;
  };
  priority: {
    coding?: Array<Record<string, unknown>>;
  };
  payee: {
    type: {
      coding?: Array<Record<string, unknown>>;
    };
    party: {
      reference?: string;
    };
  };
  facility: {
    reference?: string;
  };
  supportingInfo?: Array<Record<string, unknown>>;
  diagnosis?: Array<Record<string, unknown>>;
  procedure?: Array<Record<string, unknown>>;
  insurance?: Array<Record<string, unknown>>;
  total: {
    value?: number;
    currency?: string;
  };
}

/** Claim - Data Klaim - Asuransi Swasta — POST /Claim */
export async function claimDataKlaimAsuransiSwasta(
  client: SatuSehatClient, body: ClaimDataKlaimAsuransiSwastaBody
): Promise<FhirResource<"Claim">> {
  return client.request("POST", "/Claim", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Claim">>;
}

export interface ClaimGetClaimByNoSepParams {
    identifier?: string | number;
}

/** Claim - GET Claim by No SEP — GET /Claim/ */
export async function claimGetClaimByNoSep(
  client: SatuSehatClient, params: ClaimGetClaimByNoSepParams = {}
): Promise<FhirBundle<"Claim">> {
  return client.request("GET", "/Claim/", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"Claim">>;
}

/** GET Claim Everything — GET /Claim/{{Claim_id}}/$everything */
export async function getClaimEverything(
  client: SatuSehatClient, claimId: string
): Promise<FhirBundle<"Claim">> {
  return client.request("GET", `/Claim/${claimId}/$everything`) as Promise<FhirBundle<"Claim">>;
}

export interface ClaimresponseResponKlaimAsuransiSwastaBody {
  resourceType?: string;
  status?: string;
  identifier?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  use?: string;
  patient: {
    reference?: string;
  };
  created?: string;
  insurer: {
    reference?: string;
  };
  requestor: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
  outcome?: string;
  payeeType: {
    coding?: Array<Record<string, unknown>>;
  };
  adjudication?: Array<Record<string, unknown>>;
  item?: Array<Record<string, unknown>>;
  total?: Array<Record<string, unknown>>;
  payment: {
    type: {
      coding?: Array<Record<string, unknown>>;
    };
    date?: string;
    amount: {
      value?: number;
      currency?: string;
    };
  };
}

/** ClaimResponse - Respon Klaim - Asuransi Swasta — POST /ClaimResponse */
export async function claimresponseResponKlaimAsuransiSwasta(
  client: SatuSehatClient, body: ClaimresponseResponKlaimAsuransiSwastaBody
): Promise<FhirResource<"ClaimResponse">> {
  return client.request("POST", "/ClaimResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClaimResponse">>;
}

export interface ClaimResponseGetByNoSepParams {
    identifier?: string | number;
    request?: string | number;
}

/** Claim Response - Get By No SEP — GET /ClaimResponse/ */
export async function claimResponseGetByNoSep(
  client: SatuSehatClient, params: ClaimResponseGetByNoSepParams = {}
): Promise<FhirBundle<"ClaimResponse">> {
  return client.request("GET", "/ClaimResponse/", {
    query: { identifier: params.identifier, request: params.request },
  }) as Promise<FhirBundle<"ClaimResponse">>;
}

export interface PaymentreconcilliationRekonsiliasiPembayaranBody {
  resourceType?: string;
  status?: string;
  period: {
    start?: string;
    end?: string;
  };
  created?: string;
  paymentIssuer: {
    reference?: string;
  };
  requestor: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  paymentDate?: string;
  paymentAmount: {
    value?: number;
    currency?: string;
  };
  detail?: Array<Record<string, unknown>>;
  processNote?: Array<Record<string, unknown>>;
}

/** PaymentReconcilliation - Rekonsiliasi Pembayaran — POST /PaymentReconciliation */
export async function paymentreconcilliationRekonsiliasiPembayaran(
  client: SatuSehatClient, body: PaymentreconcilliationRekonsiliasiPembayaranBody
): Promise<FhirResource<"PaymentReconciliation">> {
  return client.request("POST", "/PaymentReconciliation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentReconciliation">>;
}

export interface PaymentnoticeNotifikasiPembayaranBody {
  resourceType?: string;
  status?: string;
  request: {
    reference?: string;
  };
  response: {
    reference?: string;
  };
  created?: string;
  paymentDate?: string;
  provider: {
    reference?: string;
  };
  payee: {
    reference?: string;
  };
  recipient: {
    reference?: string;
  };
  amount: {
    value?: number;
    currency?: string;
  };
  payment: {
    reference?: string;
  };
  paymentStatus: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** PaymentNotice - Notifikasi Pembayaran — POST /PaymentNotice */
export async function paymentnoticeNotifikasiPembayaran(
  client: SatuSehatClient, body: PaymentnoticeNotifikasiPembayaranBody
): Promise<FhirResource<"PaymentNotice">> {
  return client.request("POST", "/PaymentNotice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentNotice">>;
}

export interface GetPaymentreconciliationGetByIdClaimParams {
    detailRequest?: string | number;
}

/** GET PaymentReconciliation - GET By ID Claim — GET /PaymentReconciliation */
export async function getPaymentreconciliationGetByIdClaim(
  client: SatuSehatClient, params: GetPaymentreconciliationGetByIdClaimParams = {}
): Promise<FhirBundle<"PaymentReconciliation">> {
  return client.request("GET", "/PaymentReconciliation", {
    query: { "detail-request": params.detailRequest },
  }) as Promise<FhirBundle<"PaymentReconciliation">>;
}

export interface GetPaymentnoticeGetByIdClaimParams {
    request?: string | number;
}

/** GET PaymentNotice - GET By ID Claim — GET /PaymentNotice */
export async function getPaymentnoticeGetByIdClaim(
  client: SatuSehatClient, params: GetPaymentnoticeGetByIdClaimParams = {}
): Promise<FhirBundle<"PaymentNotice">> {
  return client.request("GET", "/PaymentNotice", {
    query: { request: params.request },
  }) as Promise<FhirBundle<"PaymentNotice">>;
}
