/**
 * klaim-swasta/secondary-payor — generated by scripts/generate-modules.mjs
 * from "25. Use Case - Modul Klaim (Asuransi Swasta).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CoverageKepesertaanAsuransiSwastaKe2Body {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  policyHolder: {
    reference?: string;
  };
  subscriber: {
    reference?: string;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - Asuransi Swasta ke-2 — POST /Coverage */
export async function coverageKepesertaanAsuransiSwastaKe2(
  client: SatuSehatClient, body: CoverageKepesertaanAsuransiSwastaKe2Body
): Promise<FhirResource<"Coverage">> {
  return client.request("POST", "/Coverage", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Coverage">>;
}

export interface CoverageMendapatkanDataKepesertaanParams {
    patient?: string | number;
    identifier?: string | number;
}

/** Coverage - Mendapatkan Data Kepesertaan — GET /Coverage */
export async function coverageMendapatkanDataKepesertaan(
  client: SatuSehatClient, params: CoverageMendapatkanDataKepesertaanParams = {}
): Promise<FhirBundle<"Coverage">> {
  return client.request("GET", "/Coverage", {
    query: { patient: params.patient, identifier: params.identifier },
  }) as Promise<FhirBundle<"Coverage">>;
}

/** Account - Menambahkan Secondary Coverage — PATCH /Account/:id */
export async function accountMenambahkanSecondaryCoverage(
  client: SatuSehatClient, id: string, operations: FhirPatchOperation[]
): Promise<FhirResource> {
  return client.request("PATCH", `/Account/${id}`, {
    body: operations,
  }) as Promise<FhirResource>;
}

export interface CoverageeligibilityrequestRequestSepKeAsuransiSwastaBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  priority: {
    coding?: Array<Record<string, unknown>>;
  };
  purpose?: Array<string>;
  patient: {
    reference?: string;
  };
  servicedDate?: string;
  created?: string;
  enterer: {
    reference?: string;
  };
  provider: {
    reference?: string;
  };
  insurer: {
    reference?: string;
  };
  facility: {
    reference?: string;
  };
  insurance?: Array<Record<string, unknown>>;
  supportingInfo?: Array<Record<string, unknown>>;
  contained?: Array<Record<string, unknown>>;
}

/** CoverageEligibilityRequest - Request SEP ke Asuransi Swasta — POST /CoverageEligibilityRequest */
export async function coverageeligibilityrequestRequestSepKeAsuransiSwasta(
  client: SatuSehatClient, body: CoverageeligibilityrequestRequestSepKeAsuransiSwastaBody
): Promise<FhirResource<"CoverageEligibilityRequest">> {
  return client.request("POST", "/CoverageEligibilityRequest", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CoverageEligibilityRequest">>;
}

export interface CoverageeligibilityrequestGetByIdentifierParams {
    identifier?: string | number;
    patient?: string | number;
}

/** CoverageEligibilityRequest - GET By Identifier — GET /CoverageEligibilityRequest */
export async function coverageeligibilityrequestGetByIdentifier(
  client: SatuSehatClient, params: CoverageeligibilityrequestGetByIdentifierParams = {}
): Promise<FhirBundle<"CoverageEligibilityRequest">> {
  return client.request("GET", "/CoverageEligibilityRequest", {
    query: { identifier: params.identifier, patient: params.patient },
  }) as Promise<FhirBundle<"CoverageEligibilityRequest">>;
}

/** CoverageEligibilityRequest - GET Everything - ClaimResponse, Claim, Invoice, ChargeItem — GET /CoverageEligibilityRequest/{{CoverageEligibilityRequest_id_2}}/$everything */
export async function coverageeligibilityrequestGetEverythingClaimresponseClaimInvoiceChargeitem(
  client: SatuSehatClient, coverageeligibilityrequestId2: string
): Promise<FhirBundle<"CoverageEligibilityRequest">> {
  return client.request("GET", `/CoverageEligibilityRequest/${coverageeligibilityrequestId2}/$everything`) as Promise<FhirBundle<"CoverageEligibilityRequest">>;
}

export interface CoverageeligibilityresponseResponseSepBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  purpose?: Array<string>;
  patient: {
    reference?: string;
  };
  created?: string;
  requestor: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  insurer: {
    reference?: string;
  };
  insurance?: Array<Record<string, unknown>>;
  extension?: Array<Record<string, unknown>>;
}

/** CoverageEligibilityResponse - Response SEP — POST /CoverageEligibilityResponse */
export async function coverageeligibilityresponseResponseSep(
  client: SatuSehatClient, body: CoverageeligibilityresponseResponseSepBody
): Promise<FhirResource<"CoverageEligibilityResponse">> {
  return client.request("POST", "/CoverageEligibilityResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"CoverageEligibilityResponse">>;
}

export interface CoverageeligibilityresponseGetByIdRequestParams {
    request?: string | number;
}

/** CoverageEligibilityResponse - GET by ID Request — GET /CoverageEligibilityResponse/ */
export async function coverageeligibilityresponseGetByIdRequest(
  client: SatuSehatClient, params: CoverageeligibilityresponseGetByIdRequestParams = {}
): Promise<FhirBundle<"CoverageEligibilityResponse">> {
  return client.request("GET", "/CoverageEligibilityResponse/", {
    query: { request: params.request },
  }) as Promise<FhirBundle<"CoverageEligibilityResponse">>;
}

export interface ChargeitemresponseParatiroidektomiParsialBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status: {
    coding?: Array<Record<string, unknown>>;
  };
  chargeItem: {
    reference?: string;
  };
  coverage: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  encounter: {
    reference?: string;
  };
  payor: {
    reference?: string;
  };
  quantity: {
    value?: number;
  };
  unitPriceOverride: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  overrideReason: {
    text?: string;
  };
  total: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
  excess: {
    amount: {
      value?: number;
      currency?: string;
    };
  };
}

/** ChargeItemResponse - Paratiroidektomi Parsial — POST /ChargeItemResponse */
export async function chargeitemresponseParatiroidektomiParsial(
  client: SatuSehatClient, body: ChargeitemresponseParatiroidektomiParsialBody
): Promise<unknown> {
  return client.request("POST", "/ChargeItemResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

export interface BillingstatusStatusBillingBody {
  resourceType?: string;
  id?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  insurer: {
    reference?: string;
  };
  recipient: {
    reference?: string;
  };
  subject: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
}

/** BillingStatus - Status Billing — POST /BillingStatus */
export async function billingstatusStatusBilling(
  client: SatuSehatClient, body: BillingstatusStatusBillingBody
): Promise<unknown> {
  return client.request("POST", "/BillingStatus", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<unknown>;
}

/** GET ChargeItem - Paratiroidektomi Parsial by ID — GET /ChargeItem/:id */
export async function getChargeitemParatiroidektomiParsialById(
  client: SatuSehatClient, id: string
): Promise<FhirResource<"ChargeItem">> {
  return client.request("GET", `/ChargeItem/${id}`) as Promise<FhirResource<"ChargeItem">>;
}

export interface InvoiceInvoiceBody {
  resourceType?: string;
  status?: string;
  subject: {
    reference?: string;
  };
  date?: string;
  issuer: {
    reference?: string;
  };
  account: {
    reference?: string;
  };
  lineItem?: Array<Record<string, unknown>>;
  totalNet: {
    value?: number;
    currency?: string;
  };
}

/** Invoice - Invoice — POST /Invoice */
export async function invoiceInvoice(
  client: SatuSehatClient, body: InvoiceInvoiceBody
): Promise<FhirResource<"Invoice">> {
  return client.request("POST", "/Invoice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Invoice">>;
}

/** Claim - Data Klaim - Asuransi Swasta — POST /Claim */
export async function claimDataKlaimAsuransiSwasta(
  client: SatuSehatClient
): Promise<FhirResource<"Claim">> {
  return client.request("POST", "/Claim") as Promise<FhirResource<"Claim">>;
}

export interface ClaimGetClaimByNoSepParams {
    identifier?: string | number;
}

/** Claim - GET Claim by No SEP — GET /Claim/ */
export async function claimGetClaimByNoSep(
  client: SatuSehatClient, params: ClaimGetClaimByNoSepParams = {}
): Promise<FhirBundle<"Claim">> {
  return client.request("GET", "/Claim/", {
    query: { identifier: params.identifier },
  }) as Promise<FhirBundle<"Claim">>;
}

/** GET Claim Everything — GET /Claim/{{Claim_id_2}}/$everything */
export async function getClaimEverything(
  client: SatuSehatClient, claimId2: string
): Promise<FhirBundle<"Claim">> {
  return client.request("GET", `/Claim/${claimId2}/$everything`) as Promise<FhirBundle<"Claim">>;
}

export interface ClaimresponseResponKlaimAsuransiSwastaBody {
  resourceType?: string;
  status?: string;
  identifier?: Array<Record<string, unknown>>;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  use?: string;
  patient: {
    reference?: string;
  };
  created?: string;
  insurer: {
    reference?: string;
  };
  requestor: {
    reference?: string;
  };
  request: {
    reference?: string;
  };
  outcome?: string;
  payeeType: {
    coding?: Array<Record<string, unknown>>;
  };
  adjudication?: Array<Record<string, unknown>>;
  item?: Array<Record<string, unknown>>;
  total?: Array<Record<string, unknown>>;
  payment: {
    type: {
      coding?: Array<Record<string, unknown>>;
    };
    date?: string;
    amount: {
      value?: number;
      currency?: string;
    };
  };
}

/** ClaimResponse - Respon Klaim - Asuransi Swasta — POST /ClaimResponse */
export async function claimresponseResponKlaimAsuransiSwasta(
  client: SatuSehatClient, body: ClaimresponseResponKlaimAsuransiSwastaBody
): Promise<FhirResource<"ClaimResponse">> {
  return client.request("POST", "/ClaimResponse", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"ClaimResponse">>;
}

export interface ClaimResponseGetByNoSepParams {
    identifier?: string | number;
    request?: string | number;
}

/** Claim Response - Get By No SEP — GET /ClaimResponse/ */
export async function claimResponseGetByNoSep(
  client: SatuSehatClient, params: ClaimResponseGetByNoSepParams = {}
): Promise<FhirBundle<"ClaimResponse">> {
  return client.request("GET", "/ClaimResponse/", {
    query: { identifier: params.identifier, request: params.request },
  }) as Promise<FhirBundle<"ClaimResponse">>;
}

export interface PaymentreconcilliationRekonsiliasiPembayaranBody {
  resourceType?: string;
  status?: string;
  period: {
    start?: string;
    end?: string;
  };
  created?: string;
  paymentIssuer: {
    reference?: string;
  };
  requestor: {
    reference?: string;
  };
  outcome?: string;
  disposition?: string;
  paymentDate?: string;
  paymentAmount: {
    value?: number;
    currency?: string;
  };
  detail?: Array<Record<string, unknown>>;
  processNote?: Array<Record<string, unknown>>;
}

/** PaymentReconcilliation - Rekonsiliasi Pembayaran — POST /PaymentReconciliation */
export async function paymentreconcilliationRekonsiliasiPembayaran(
  client: SatuSehatClient, body: PaymentreconcilliationRekonsiliasiPembayaranBody
): Promise<FhirResource<"PaymentReconciliation">> {
  return client.request("POST", "/PaymentReconciliation", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentReconciliation">>;
}

export interface PaymentnoticeNotifikasiPembayaranBody {
  resourceType?: string;
  status?: string;
  request: {
    reference?: string;
  };
  response: {
    reference?: string;
  };
  created?: string;
  paymentDate?: string;
  provider: {
    reference?: string;
  };
  payee: {
    reference?: string;
  };
  recipient: {
    reference?: string;
  };
  amount: {
    value?: number;
    currency?: string;
  };
  payment: {
    reference?: string;
  };
  paymentStatus: {
    coding?: Array<Record<string, unknown>>;
  };
}

/** PaymentNotice - Notifikasi Pembayaran — POST /PaymentNotice */
export async function paymentnoticeNotifikasiPembayaran(
  client: SatuSehatClient, body: PaymentnoticeNotifikasiPembayaranBody
): Promise<FhirResource<"PaymentNotice">> {
  return client.request("POST", "/PaymentNotice", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"PaymentNotice">>;
}

export interface GetPaymentreconciliationGetByIdClaimParams {
    detailRequest?: string | number;
}

/** GET PaymentReconciliation - GET By ID Claim — GET /PaymentReconciliation */
export async function getPaymentreconciliationGetByIdClaim(
  client: SatuSehatClient, params: GetPaymentreconciliationGetByIdClaimParams = {}
): Promise<FhirBundle<"PaymentReconciliation">> {
  return client.request("GET", "/PaymentReconciliation", {
    query: { "detail-request": params.detailRequest },
  }) as Promise<FhirBundle<"PaymentReconciliation">>;
}

export interface PaymentnoticeGetByIdClaimParams {
    request?: string | number;
}

/** PaymentNotice - GET By ID Claim — GET /PaymentNotice */
export async function paymentnoticeGetByIdClaim(
  client: SatuSehatClient, params: PaymentnoticeGetByIdClaimParams = {}
): Promise<FhirBundle<"PaymentNotice">> {
  return client.request("GET", "/PaymentNotice", {
    query: { request: params.request },
  }) as Promise<FhirBundle<"PaymentNotice">>;
}
