/**
 * klaim-swasta/tpa — generated by scripts/generate-modules.mjs
 * from "25. Use Case - Modul Klaim (Asuransi Swasta).postman_collection.json". Re-run `npm run generate` instead of hand-editing.
 *
 * Request body types are inferred from the collection's example bodies (leaf
 * fields optional). Response types use the shared FHIR helpers where the
 * endpoint is unambiguous, otherwise `unknown`.
 */
import type { SatuSehatClient } from "../core/client.js";
import type { FhirBundle, FhirPatchOperation, FhirResource } from "../fhir/types.js";

export interface CoverageKepesertaanAsuransiSwastaYangMenggunakanTpaBody {
  resourceType?: string;
  identifier?: Array<Record<string, unknown>>;
  status?: string;
  type: {
    coding?: Array<Record<string, unknown>>;
  };
  policyHolder: {
    reference?: string;
  };
  subscriber: {
    reference?: string;
  };
  subscriberId?: string;
  beneficiary: {
    reference?: string;
  };
  payor?: Array<Record<string, unknown>>;
  class?: Array<Record<string, unknown>>;
}

/** Coverage - Kepesertaan - Asuransi Swasta yang menggunakan TPA — POST /Coverage */
export async function coverageKepesertaanAsuransiSwastaYangMenggunakanTpa(
  client: SatuSehatClient, body: CoverageKepesertaanAsuransiSwastaYangMenggunakanTpaBody
): Promise<FhirResource<"Coverage">> {
  return client.request("POST", "/Coverage", {
    body: body as unknown as Record<string, unknown>,
  }) as Promise<FhirResource<"Coverage">>;
}
